# Generated by Django 4.0.8 on 2023-01-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidants_connect_pico_cms', '0002_mandatetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published', models.BooleanField(verbose_name='Publié')),
                ('slug', models.SlugField(verbose_name='Clé d’URL')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='Tri')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Introduction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Catégorie FAQ',
                'verbose_name_plural': 'Catégories FAQ',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published', models.BooleanField(verbose_name='Publié')),
                ('slug', models.SlugField(verbose_name='Clé d’URL')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='Tri')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('question', models.TextField(verbose_name='Question')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidants_connect_pico_cms.faqcategory', verbose_name='Catégorie')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Question FAQ',
                'verbose_name_plural': 'Questions FAQ',
            },
        ),
    ]
