# Generated by Django 4.0.10 on 2023-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0003_faqcategory_faqquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='body',
            field=models.TextField(verbose_name='Réponse'),
        ),
    ]
