# Generated by Django 4.0.10 on 2023-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0003_faqcategory_faqquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqcategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(help_text='Par exemple <code>questions-generales</code> pour « Questions générales ».<br>Sera utilisée pour créer des liens vers cet élément de contenu.<br>50 caractères maximum.', verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='body',
            field=models.TextField(verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='slug',
            field=models.SlugField(help_text='Par exemple <code>questions-generales</code> pour « Questions générales ».<br>Sera utilisée pour créer des liens vers cet élément de contenu.<br>50 caractères maximum.', verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(help_text='Par exemple <code>questions-generales</code> pour « Questions générales ».<br>Sera utilisée pour créer des liens vers cet élément de contenu.<br>50 caractères maximum.', verbose_name='Clé d’URL'),
        ),
    ]
