# Generated by Django 4.2 on 2023-04-11 08:12

from django.db import migrations

import aidants_connect_pico_cms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0005_alter_mandatetranslation_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='body',
            field=aidants_connect_pico_cms.fields.MarkdownField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='mandatetranslation',
            name='body',
            field=aidants_connect_pico_cms.fields.MarkdownField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='body',
            field=aidants_connect_pico_cms.fields.MarkdownField(verbose_name='Contenu'),
        ),
    ]
