# Generated by Django 4.2.4 on 2023-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0006_alter_faqcategory_body_alter_mandatetranslation_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='profile_picture_url',
            field=models.URLField(default=None, null=True, verbose_name='URL vers la photo de profil de la personne qui témoigne'),
        ),
    ]
