# Generated by Django 4.2.4 on 2023-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0007_testimony_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='quote',
            field=models.CharField(default='', max_length=255, verbose_name="Citation à afficher sur la page d'accueil"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(help_text='Par exemple <code>questions-generales</code> pour « Questions générales ».<br>Sera utilisée pour créer des liens vers cet élément de contenu.<br>50 caractères maximum.', unique=True, verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='slug',
            field=models.SlugField(help_text='Par exemple <code>questions-generales</code> pour « Questions générales ».<br>Sera utilisée pour créer des liens vers cet élément de contenu.<br>50 caractères maximum.', unique=True, verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(help_text='Par exemple <code>questions-generales</code> pour « Questions générales ».<br>Sera utilisée pour créer des liens vers cet élément de contenu.<br>50 caractères maximum.', unique=True, verbose_name='Clé d’URL'),
        ),
    ]
