# Generated by Django 4.2.8 on 2024-01-18 11:48

import django.db.models.deletion
from django.db import migrations, models

import aidants_connect_pico_cms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0008_testimony_quote_alter_faqcategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published', models.BooleanField(verbose_name='Publié')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='Tri')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('body', aidants_connect_pico_cms.fields.MarkdownField(blank=True, default='', verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Sous-catégorie FAQ',
                'verbose_name_plural': 'Sous-catégories FAQ',
            },
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='body',
            field=aidants_connect_pico_cms.fields.MarkdownField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='body',
            field=aidants_connect_pico_cms.fields.MarkdownField(verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_pico_cms.faqcategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_pico_cms.faqsubcategory', verbose_name='Sous-catégorie'),
        ),
    ]
