# Generated by Django 4.2.8 on 2024-01-23 15:34
from re import escape, search

from django.db import migrations, models
from django.utils.text import slugify

import aidants_connect_pico_cms.fields
from aidants_connect_pico_cms.utils import compute_correct_slug


def gen_slug(apps, _):
    for model_name in ("FaqCategory", "FaqSubCategory"):
        model = apps.get_model("aidants_connect_pico_cms", model_name)
        for item in model.objects.filter(slug__isnull=True):
            item.slug = compute_correct_slug(model, item.name)
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0009_faqsubcategory_alter_faqcategory_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqsubcategory',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True, verbose_name='Clé d’URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='body',
            field=aidants_connect_pico_cms.fields.MarkdownField(blank=True, default='', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True, verbose_name='Clé d’URL'),
        ),
        migrations.RunPython(
            gen_slug, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='faqsubcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Clé d’URL'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Clé d’URL'),
        ),
    ]
