# Generated by Django 4.2.9 on 2024-01-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0010_faqsubcategory_slug_alter_faqcategory_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidants_connect_pico_cms.faqcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidants_connect_pico_cms.faqsubcategory', verbose_name='Sous-catégorie'),
        ),
    ]
