# Generated by Django 4.2.17 on 2025-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_pico_cms', '0013_alter_mandatetranslation_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='theme',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('aidant', 'Aidant'), ('referent', 'Référent')], max_length=30, null=True, verbose_name='Thème'),
        ),
    ]
