# Generated by Django 3.1.13 on 2022-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aidants_connect_web", "0050_auto_20210321_2154"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                ("email", models.EmailField(max_length=150)),
                (
                    "profession",
                    models.CharField(max_length=150, verbose_name="Intitulé du poste"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouvelle"),
                            ("PROCESSING", "En cours"),
                            ("VALIDATED", "Validée"),
                            ("REFUSED", "Refusée"),
                            ("CANCELLED", "Annulée"),
                            ("CHANGES_REQUIRED", "Changements demandés"),
                        ],
                        default="NEW",
                        max_length=150,
                        verbose_name="État",
                    ),
                ),
                (
                    "type_other",
                    models.CharField(
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Type de structure si autre",
                    ),
                ),
                (
                    "name",
                    models.TextField(default="No name provided", verbose_name="Nom"),
                ),
                ("siret", models.BigIntegerField(default=1, verbose_name="N° SIRET")),
                (
                    "address",
                    models.TextField(
                        default="No address provided", verbose_name="Adresse"
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Code Postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=255, null=True, verbose_name="Ville"),
                ),
                (
                    "partner_administration",
                    models.CharField(
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Administration partenaire",
                    ),
                ),
                (
                    "public_service_delegation_attestation",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="",
                        verbose_name="Attestation de délégation de service public",
                    ),
                ),
                (
                    "france_services_label",
                    models.BooleanField(
                        default=False, verbose_name="Labellisation France Services"
                    ),
                ),
                (
                    "web_site",
                    models.URLField(default=None, null=True, verbose_name="Site web"),
                ),
                (
                    "mission_description",
                    models.TextField(
                        verbose_name="Description des missions de la structure"
                    ),
                ),
                (
                    "avg_nb_demarches",
                    models.IntegerField(
                        verbose_name="Nombre moyen de démarches ou de dossiers traités par semaine"
                    ),
                ),
                (
                    "manager_first_name",
                    models.CharField(max_length=150, verbose_name="Prénom"),
                ),
                (
                    "manager_last_name",
                    models.CharField(max_length=150, verbose_name="Nom"),
                ),
                ("manager_email", models.EmailField(max_length=150)),
                (
                    "manager_profession",
                    models.CharField(max_length=150, verbose_name="Intitulé du poste"),
                ),
                (
                    "manager_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("cgu", models.BooleanField(verbose_name="J'accepte les CGU")),
                ("dpo", models.BooleanField(verbose_name="Le DPO est informé")),
                (
                    "professionals_only",
                    models.BooleanField(
                        verbose_name="La structure ne contient que des aidants professionnels"
                    ),
                ),
                (
                    "without_elected",
                    models.BooleanField(
                        verbose_name="Aucun élu n'est impliqué dans la structure"
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_requests",
                        to="aidants_connect_habilitation.issuer",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aidants_connect_web.organisationtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("AC", "Aidants Connect"), ("ISSUER", "Demandeur")],
                        max_length=20,
                        verbose_name="Expéditeur",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message")),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aidants_connect_habilitation.organisationrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AidantRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                ("email", models.EmailField(max_length=150)),
                (
                    "profession",
                    models.CharField(max_length=150, verbose_name="Intitulé du poste"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aidant_requests",
                        to="aidants_connect_habilitation.organisationrequest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="organisationrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_negated=True, type_id=12),
                        ("type_other__isnull", True),
                    ),
                    models.Q(("type_id", 12), ("type_other__isnull", False)),
                    _connector="OR",
                ),
                name="type_other_correctly_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationrequest",
            constraint=models.CheckConstraint(
                check=models.Q(cgu=True), name="cgu_checked"
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationrequest",
            constraint=models.CheckConstraint(
                check=models.Q(dpo=True), name="dpo_checked"
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationrequest",
            constraint=models.CheckConstraint(
                check=models.Q(professionals_only=True),
                name="professionals_only_checked",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationrequest",
            constraint=models.CheckConstraint(
                check=models.Q(without_elected=True), name="without_elected_checked"
            ),
        ),
    ]
