# Generated by Django 3.2.11 on 2022-01-13 09:24

import django.db.models.deletion
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_habilitation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuer",
            options={"verbose_name": "Demandeur"},
        ),
        migrations.AlterModelOptions(
            name="organisationrequest",
            options={
                "verbose_name": "Demande d’habilitation",
                "verbose_name_plural": "Demandes d’habilitation",
            },
        ),
        migrations.AlterField(
            model_name="issuer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisation_requests",
                to="aidants_connect_habilitation.issuer",
                verbose_name="Demandeur",
            ),
        ),
    ]
