# Generated by Django 3.2.11 on 2022-01-13 17:11

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_habilitation", "0002_auto_20220113_1024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aidantrequest",
            options={
                "verbose_name": "aidant à habiliter",
                "verbose_name_plural": "aidants à habiliter",
            },
        ),
        migrations.AlterModelOptions(
            name="requestmessage",
            options={"verbose_name": "message"},
        ),
        migrations.RemoveField(
            model_name="aidantrequest",
            name="phone",
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="manager_email",
            field=models.EmailField(
                max_length=150, verbose_name="Email du responsable"
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="manager_first_name",
            field=models.CharField(
                max_length=150, verbose_name="Prénom du responsable"
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="manager_last_name",
            field=models.CharField(max_length=150, verbose_name="Nom du responsable"),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="manager_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Téléphone du responsable",
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="manager_profession",
            field=models.CharField(
                max_length=150, verbose_name="Profession du responsable"
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="name",
            field=models.TextField(
                default="No name provided", verbose_name="Nom de la structure"
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="public_service_delegation_attestation",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="",
                verbose_name="Attestation de délégation de service public",
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="type_other",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Type de structure si autre",
            ),
        ),
    ]
