# Generated by Django 3.2.11 on 2022-02-10 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_habilitation", "0005_auto_20220131_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuer",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email vérifié"),
        ),
        migrations.CreateModel(
            name="IssuerEmailConfirmation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Créé le"
                    ),
                ),
                ("sent", models.DateTimeField(null=True, verbose_name="Envoyée")),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="Clé"),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aidants_connect_habilitation.issuer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmation d'email",
                "verbose_name_plural": "Confirmations d'email",
            },
        ),
    ]
