# Generated by Django 3.2.12 on 2022-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0006_auto_20220210_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidantrequest',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email nominatif'),
        ),
        migrations.AlterField(
            model_name='dataprivacyofficer',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email nominatif'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email nominatif'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email nominatif'),
        ),
    ]
