# Generated by Django 3.2.12 on 2022-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0007_auto_20220223_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='cgu',
            field=models.BooleanField(default=False, verbose_name="J'accepte les CGU"),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='dpo',
            field=models.BooleanField(default=False, verbose_name='Le DPO est informé'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='professionals_only',
            field=models.BooleanField(default=False, verbose_name='La structure ne contient que des aidants professionnels'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='without_elected',
            field=models.BooleanField(default=False, verbose_name="Aucun élu n'est impliqué dans la structure"),
        ),
    ]
