# Generated by Django 3.2.12 on 2022-03-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0008_auto_20220228_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueremailconfirmation',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmations', to='aidants_connect_habilitation.issuer'),
        ),
    ]
