# Generated by Django 3.2.12 on 2022-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0009_alter_issueremailconfirmation_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='siret',
            field=models.BigIntegerField(verbose_name='N° SIRET'),
        ),
    ]
