# Generated by Django 3.2.12 on 2022-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0010_alter_organisationrequest_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Brouillon'), ('AC_VALIDATION_PROCESSING', 'En attente de validation par Aidants Connect'), ('VALIDATED', 'Validée'), ('REFUSED', 'Refusée'), ('CLOSED', 'Clôturée'), ('CHANGES_REQUIRED', 'Modifications demandées'), ('CHANGES_PROPOSED', 'Modifications proposées par Aidants Connect')], default='NEW', max_length=150, verbose_name='État'),
        ),
    ]
