# Generated by Django 3.2.12 on 2022-03-14 14:30

from django.db import migrations

import aidants_connect_habilitation.models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0011_alter_organisationrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataprivacyofficer',
            options={'verbose_name': 'DPO', 'verbose_name_plural': 'DPOs'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Responsable structure', 'verbose_name_plural': 'Responsables structure'},
        ),
        migrations.AlterField(
            model_name='aidantrequest',
            name='email',
            field=aidants_connect_habilitation.models.PersonEmailField(max_length=150, verbose_name='Email nominatif'),
        ),
        migrations.AlterField(
            model_name='dataprivacyofficer',
            name='email',
            field=aidants_connect_habilitation.models.PersonEmailField(max_length=150, verbose_name='Email nominatif'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='email',
            field=aidants_connect_habilitation.models.PersonEmailField(max_length=150, unique=True, verbose_name='Email nominatif'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=aidants_connect_habilitation.models.PersonEmailField(max_length=150, verbose_name='Email nominatif'),
        ),
        migrations.AlterUniqueTogether(
            name='aidantrequest',
            unique_together={('email', 'organisation')},
        ),
    ]
