# Generated by Django 3.2.12 on 2022-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0012_auto_20220314_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='is_private_org',
            field=models.BooleanField(default=False, verbose_name='Structure privée'),
        ),
    ]
