# Generated by Django 3.2.12 on 2022-03-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0013_auto_20220321_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='france_services_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Numéro d’immatriculation France Services'),
        ),
        migrations.AddField(
            model_name='organisationrequest',
            name='is_private_org',
            field=models.BooleanField(default=False, verbose_name='Structure privée'),
        ),
        migrations.AddConstraint(
            model_name='organisationrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_private_org', True), ('partner_administration__isnull_or_blank', False)), models.Q(('is_private_org', False), ('partner_administration__isnull_or_blank', True)), _connector='OR'), name='partner_administration_if_org_is_private'),
        ),
        migrations.AddConstraint(
            model_name='organisationrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('france_services_label', True), ('france_services_number__isnull_or_blank', False)), models.Q(('france_services_label', False), ('france_services_number__isnull_or_blank', True)), _connector='OR'), name='immatriculation_number_if_france_services_label'),
        ),
    ]
