# Generated by Django 3.2.12 on 2022-03-31 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0014_auto_20220324_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
