# Generated by Django 3.2.12 on 2022-04-05 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0015_remove_dpo_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'message'},
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
