# Generated by Django 3.2.12 on 2022-04-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0085_auto_20220329_0005'),
        ('aidants_connect_habilitation', '0017_auto_20220405_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidants_connect_web.organisation'),
        ),
    ]
