# Generated by Django 3.2.12 on 2022-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0018_organisationrequest_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='organisationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification'),
        ),
    ]
