# Generated by Django 3.2.12 on 2022-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0019_auto_20220420_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification'),
        ),
    ]
