# Generated by Django 3.2.12 on 2022-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0021_auto_20220627_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE'),
        ),
    ]
