# Generated by Django 3.2.12 on 2022-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0022_organisationrequest_codeinsee'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE'),
        ),
    ]
