# Generated by Django 3.2.12 on 2022-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0023_manager_codeinsee'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='dep_codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Département Code INSEE'),
        ),
        migrations.AddField(
            model_name='organisationrequest',
            name='dep_codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Département Code INSEE'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Commune Code INSEE'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Commune Code INSEE'),
        ),
    ]
