# Generated by Django 3.2.15 on 2022-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0024_auto_20220809_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationrequest',
            old_name='codeinsee',
            new_name='city_insee_code'
        ),
        migrations.RenameField(
            model_name='organisationrequest',
            old_name='dep_codeinsee',
            new_name='department_insee_code'
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='city_insee_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE de la ville'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='department_insee_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE du département'),
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='codeinsee',
            new_name='city_insee_code'
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='dep_codeinsee',
            new_name='department_insee_code'
        ),
        migrations.AlterField(
            model_name='manager',
            name='city_insee_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE de la ville'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department_insee_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE du département'),
        ),
    ]
