# Generated by Django 4.2.3 on 2023-07-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0025_auto_20220822_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Référent structure', 'verbose_name_plural': 'Référents structure'},
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='manager',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='aidants_connect_habilitation.manager', verbose_name='Référent'),
        ),
    ]
