# Generated by Django 4.2.10 on 2024-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0027_aidantrequest_habilitation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Brouillon'), ('AC_VALIDATION_PROCESSING', 'En attente de validation par Aidants Connect'), ('VALIDATED', 'Élégibilité validée'), ('REFUSED', 'Refusée'), ('CLOSED', 'Clôturée'), ('CHANGES_REQUIRED', 'Modifications demandées'), ('CHANGES_PROPOSED', 'Modifications proposées par Aidants Connect')], default='NEW', max_length=150, verbose_name='État'),
        ),
    ]
