# Generated by Django 4.2.11 on 2024-03-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0061_alter_coreferentnonaidantrequest_status_and_more'),
        ('aidants_connect_habilitation', '0028_aidantrequest_conseiller_numerique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='habilitation_request',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manger_request', to='aidants_connect_web.habilitationrequest'),
        ),
        migrations.RunSQL(
            """
            UPDATE aidants_connect_habilitation_manager m
            SET habilitation_request_id = hr.id
            FROM aidants_connect_web_habilitationrequest hr
            WHERE LOWER(m.email) = LOWER(hr.email)
            """,
            elidable=True
        ),
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.CheckConstraint(check=models.Q(('is_aidant', True), ('habilitation_request__isnull', True), _connector='OR'), name='habilitation_request_null_when_manager_is_not_aidant'),
        ),
    ]
