# Generated by Django 4.2.11 on 2024-04-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0064_referentsformation_livestorm_id'),
        ('aidants_connect_habilitation', '0029_manager_habilitation_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidantrequest',
            name='habilitation_request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aidant_request', to='aidants_connect_web.habilitationrequest'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='habilitation_request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manger_request', to='aidants_connect_web.habilitationrequest'),
        ),
    ]
