# Generated by Django 4.2.15 on 2024-08-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0030_alter_aidantrequest_habilitation_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='legal_category',
            field=models.CharField(default="0",
                                   max_length=30,
                                   verbose_name='categorieJuridiqueUniteLegale'),
        ),
    ]
