# Generated by Django 4.2.15 on 2024-09-11 09:45

from django.db import migrations, models


def migrate_not_free_field(apps, _):
    OrganisationRequest = apps.get_model(
        "aidants_connect_habilitation", "OrganisationRequest"
    )

    OrganisationRequest.objects.update(not_free=True)

class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_habilitation", "0031_organisationrequest_legal_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationrequest",
            name="not_free",
            field=models.BooleanField(default=False, verbose_name="La formation est payante"),
        ),
        migrations.RunPython(migrate_not_free_field, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="organisationrequest",
            constraint=models.CheckConstraint(check=models.Q(("status", "NEW"), models.Q(models.Q(("status", "NEW"), _negated=True), ("not_free", True)), _connector="OR"), name="not_free_checked"),
        ),
    ]
