# Generated by Django 4.2.17 on 2025-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0033_alter_organisationrequest_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.CheckConstraint(check=models.Q(('is_aidant', True), ('habilitation_request__isnull', True), _connector='OR'), name='habilitation_request_null_when_manager_is_not_aidant'),
        ),
    ]
