# Generated by Django 4.2.23 on 2025-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0033_alter_organisationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Complément d'adresse"),
        ),
    ]
