# Generated by Django 4.2.23 on 2025-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0034_organisationrequest_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Complément d'adresse"),
        ),
    ]
