# Generated by Django 4.2.23 on 2025-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0035_manager_address_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='conseiller_numerique',
            field=models.BooleanField(blank=True, default=False, verbose_name='Est un conseiller numérique'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='is_aidant',
            field=models.BooleanField(blank=True, default=False, verbose_name="C'est aussi un aidant"),
        ),
        migrations.AlterField(
            model_name='manager',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal'),
        ),
    ]
