# Generated by Django 4.2.23 on 2025-10-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0035_manager_address_complement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='address_complement',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='city_insee_code',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='department_insee_code',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='zipcode',
        ),
    ]
