# Generated by Django 4.2.23 on 2025-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0036_alter_manager_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='avg_nb_demarches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre moyen de démarches ou de dossiers traités par semaine'),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='mission_description',
            field=models.TextField(blank=True, default='', verbose_name='Description des missions de la structure'),
        ),
    ]
