# Generated by Django 4.2.30 on 2026-07-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_habilitation', '0037_alter_organisationrequest_avg_nb_demarches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='invalid_siret',
            field=models.BooleanField(default=False, verbose_name='Siret Invalide'),
        ),
    ]
