# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: end-of-file-fixer
