# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
    - id: missing-django-migrations
      name: Check for missing django migrations
      entry: env PIPENV_VERBOSITY=-1 pipenv run python manage.py makemigrations --no-input --dry-run --check
      language: system
      pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
