# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
    - id: missing-django-migrations
      name: Check for missing django migrations
      entry: env PIPENV_VERBOSITY=-1 pipenv run python manage.py makemigrations --no-input --dry-run --check
      language: system
      pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: end-of-file-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.1.1
    hooks:
    - id: djade
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.1.0
    hooks:
    - id: biome-check
      additional_dependencies:
      - "@biomejs/biome"
