[tool.black]
exclude = '''
(
    /(
        \.direnv
        | \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.nox
        | \.tox
        | \.venv
        | venv
        | \.svn
        | _build
        | buck-out
        | build
        | dist
        | aidants_connect_web/migrations/*
    )/
)
'''
