# Generated by Django 4.2.3 on 2023-07-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otp_static', '0002_throttling'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidantConnectStaticDevice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_static.staticdevice',),
        ),
    ]
