# Generated by Django 3.1.1 on 2021-01-11 16:04

import aidants_connect_web.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# aidants_connect_web.migrations.0010_auto_20191119_1105
# aidants_connect_web.migrations.0019_normalize_usager_data
# aidants_connect_web.migrations.0040_journal_migrate_aidant_and_usager

class Migration(migrations.Migration):

    replaces = [('aidants_connect_web', '0001_initial'), ('aidants_connect_web', '0002_journal'), ('aidants_connect_web', '0003_auto_20190827_1432'), ('aidants_connect_web', '0004_one_mandat_per_demarche'), ('aidants_connect_web', '0005_auto_20190830_1837'), ('aidants_connect_web', '0006_auto_20190830_1846'), ('aidants_connect_web', '0007_mandat_modified_by_access_token'), ('aidants_connect_web', '0008_auto_20191021_1404'), ('aidants_connect_web', '0009_auto_20191119_1056'), ('aidants_connect_web', '0010_auto_20191119_1105'), ('aidants_connect_web', '0011_remove_mandat_duree'), ('aidants_connect_web', '0012_organisations'), ('aidants_connect_web', '0013_null_birthplace'), ('aidants_connect_web', '0014_auto_20200213_1706'), ('aidants_connect_web', '0015_add_ordering_and_related_names'), ('aidants_connect_web', '0016_rename_expiresOn'), ('aidants_connect_web', '0017_journal_action_add_franceconnection_usager'), ('aidants_connect_web', '0018_add_journal_action_print_mandat'), ('aidants_connect_web', '0019_normalize_usager_data'), ('aidants_connect_web', '0020_journal_action_add_update_email_usager'), ('aidants_connect_web', '0021_remote_mandat'), ('aidants_connect_web', '0022_auto_20200515_1455'), ('aidants_connect_web', '0023_connection_mandat_is_remote'), ('aidants_connect_web', '0024_rename_mandat_print'), ('aidants_connect_web', '0025_rename_mandat_step1_prepare_fk'), ('aidants_connect_web', '0026_rename_mandat_step2'), ('aidants_connect_web', '0027_rename_mandat_step3'), ('aidants_connect_web', '0028_rename_mandat_step4'), ('aidants_connect_web', '0029_fix_related_names'), ('aidants_connect_web', '0030_rename_is_remote_mandat_field'), ('aidants_connect_web', '0031_remove_indexes_with_mandat'), ('aidants_connect_web', '0032_allow_indexes_with_autorisation'), ('aidants_connect_web', '0033_add_new_mandat_model'), ('aidants_connect_web', '0034_add_related_names'), ('aidants_connect_web', '0035_add_autorisation_revocation_date'), ('aidants_connect_web', '0036_remove_autorisation_last_renewal_date'), ('aidants_connect_web', '0037_auto_20200605_1658'), ('aidants_connect_web', '0038_post_migration_cleanup'), ('aidants_connect_web', '0039_journal_add_foreign_keys'), ('aidants_connect_web', '0040_journal_migrate_aidant_and_usager'), ('aidants_connect_web', '0041_journal_remove_initiator_and_usager'), ('aidants_connect_web', '0042_journal_rename_usager'), ('aidants_connect_web', '0043_auto_20201118_1601'), ('aidants_connect_web', '0044_auto_20210111_1659')]

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aidant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profession', models.TextField()),
                ('organisme', models.TextField()),
                ('ville', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'aidant',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.TextField()),
                ('family_name', models.TextField()),
                ('preferred_username', models.TextField(blank=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'Femme'), ('male', 'Homme')], default='F', max_length=6)),
                ('birthplace', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(9999), django.core.validators.MaxValueValidator(100000)])),
                ('birthcountry', models.IntegerField(default=99100, validators=[django.core.validators.MinValueValidator(99100), django.core.validators.MaxValueValidator(99500)])),
                ('sub', models.TextField(unique=True)),
                ('email', models.EmailField(default='noemailprovided@aidantconnect.beta.gouv.fr', max_length=254)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree', models.IntegerField(default=3)),
                ('aidant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.usager')),
                ('demarche', models.CharField(default='No démarche', max_length=100)),
                ('last_mandat_renewal_token', models.TextField(default='No token provided')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_mandat_renewal_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('aidant', 'demarche', 'usager')},
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat")], max_length=30)),
                ('initiator', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('usager', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('demarche', models.CharField(blank=True, max_length=100, null=True)),
                ('mandat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('code', models.TextField()),
                ('nonce', models.TextField(default='No Nonce Provided')),
                ('expiresOn', models.DateTimeField(default=aidants_connect_web.models.default_connection_expiration_date)),
                ('access_token', models.TextField(default='No token Provided')),
                ('connection_type', models.CharField(choices=[('FS', 'FC as FS'), ('FI', 'FC as FI')], default='FI', max_length=2)),
                ('demarche', models.TextField(default='No demarche provided')),
                ('complete', models.BooleanField(default=False)),
                ('usager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.usager')),
                ('aidant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.mandat')),
                ('demarches', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='No démarche'), null=True, size=None)),
                ('duree', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='duree',
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='No name provided')),
                ('siret', models.PositiveIntegerField(default=1)),
                ('address', models.TextField(default='No address provided')),
            ],
        ),
        migrations.RemoveField(
            model_name='aidant',
            name='organisme',
        ),
        migrations.RemoveField(
            model_name='aidant',
            name='ville',
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat"), ('update_mandat', "Renouvellement d'un mandat")], max_length=30),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthplace',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(9999), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthplace',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthplace',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat"), ('update_mandat', "Renouvellement d'un mandat"), ('cancel_mandat', "Révocation d'un mandat")], max_length=30),
        ),
        migrations.AlterModelOptions(
            name='usager',
            options={'ordering': ['family_name', 'given_name']},
        ),
        migrations.AddField(
            model_name='aidant',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aidants', to='aidants_connect_web.organisation'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='aidant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagers', to='aidants_connect_web.mandat'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='usager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagers', to='aidants_connect_web.usager'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='aidant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='usager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='aidants_connect_web.usager'),
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='expiresOn',
            new_name='expires_on',
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat"), ('update_mandat', "Renouvellement d'un mandat"), ('cancel_mandat', "Révocation d'un mandat")], max_length=30),
        ),
        migrations.AddField(
            model_name='journal',
            name='mandat_print_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('create_mandat_print', "Création d'un mandat papier"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat"), ('update_mandat', "Renouvellement d'un mandat"), ('cancel_mandat', "Révocation d'un mandat")], max_length=30),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthcountry',
            field=models.CharField(default='99100', max_length=5),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthplace',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usager',
            name='gender',
            field=models.CharField(choices=[('female', 'Femme'), ('male', 'Homme')], default='female', max_length=6),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('create_mandat_print', "Création d'un mandat papier"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat"), ('update_mandat', "Renouvellement d'un mandat"), ('cancel_mandat', "Révocation d'un mandat")], max_length=30),
        ),
        migrations.AddField(
            model_name='journal',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='is_remote_mandat',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='duree',
        ),
        migrations.AddField(
            model_name='connection',
            name='duree_keyword',
            field=models.CharField(choices=[('SHORT', 'pour une durée de 1 jour'), ('LONG', 'pour une durée de 1 an'), ('EUS_03_20', 'jusqu’à la fin de l’état d’urgence sanitaire déclaré par l’article 4 de la loi du 23 mars 2020.')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_remote_mandat',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'connexion'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'entrée de journal', 'verbose_name_plural': 'entrées de journal'},
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_remote_mandat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='duree_keyword',
            field=models.CharField(choices=[('SHORT', 'pour une durée de 1 jour'), ('LONG', 'pour une durée de 1 an'), ('EUS_03_20', 'jusqu’à la fin de l’état d’urgence sanitaire ')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='mandat_is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='mandat_print_hash',
            new_name='attestation_hash',
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('create_attestation', "Création d'une attestation"), ('create_mandat', "Création d'un mandat"), ('use_mandat', "Utilisation d'un mandat"), ('update_mandat', "Renouvellement d'un mandat"), ('cancel_mandat', "Révocation d'un mandat")], max_length=30),
        ),
        migrations.RenameModel(
            old_name='Mandat',
            new_name='Autorisation',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='mandat',
            new_name='autorisation',
        ),
        migrations.AlterField(
            model_name='connection',
            name='autorisation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='access_token',
            field=models.TextField(default='No token provided'),
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='mandat',
            new_name='autorisation',
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('create_attestation', "Création d'une attestation"), ('create_autorisation', "Création d'une autorisation"), ('use_autorisation', "Utilisation d'une autorisation"), ('update_autorisation', "Renouvellement d'une autorisation"), ('cancel_autorisation', "Révocation d'une autorisation")], max_length=30),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='aidant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='usager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='aidants_connect_web.usager'),
        ),
        migrations.RenameField(
            model_name='autorisation',
            old_name='last_mandat_renewal_date',
            new_name='last_renewal_date',
        ),
        migrations.RenameField(
            model_name='autorisation',
            old_name='last_mandat_renewal_token',
            new_name='last_renewal_token',
        ),
        migrations.AlterField(
            model_name='connection',
            name='autorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usagers', to='aidants_connect_web.autorisation'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='aidant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='autorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='aidants_connect_web.autorisation'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='usager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='aidants_connect_web.usager'),
        ),
        migrations.RenameField(
            model_name='autorisation',
            old_name='is_remote_mandat',
            new_name='is_remote',
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='aidant',
            field=models.ForeignKey(db_index=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='usager',
            field=models.ForeignKey(db_index=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='aidants_connect_web.usager'),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='aidant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='usager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='aidants_connect_web.usager'),
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(default=aidants_connect_web.models.get_staff_organisation_name_id, on_delete=django.db.models.deletion.PROTECT, related_name='mandats', to='aidants_connect_web.organisation')),
                ('usager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='aidants_connect_web.usager')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree_keyword', models.CharField(choices=[('SHORT', 'pour une durée de 1 jour'), ('LONG', 'pour une durée de 1 an'), ('EUS_03_20', 'jusqu’à la fin de l’état d’urgence sanitaire ')], max_length=16, null=True)),
                ('is_remote', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='autorisation',
            name='mandat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='aidants_connect_web.mandat'),
        ),
        migrations.AddField(
            model_name='autorisation',
            name='revocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='autorisation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='autorisation',
            name='last_renewal_date',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(default='No address provided', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.TextField(default='No name provided', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='siret',
            field=models.PositiveIntegerField(default=1, verbose_name='N° SIRET'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='given_name',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='family_name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='preferred_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usager',
            name='gender',
            field=models.CharField(choices=[('female', 'Femme'), ('male', 'Homme')], default='female', max_length=6, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthdate',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthplace',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='birthcountry',
            field=models.CharField(default='99100', max_length=5, verbose_name='Pays de naissance'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='usager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats', to='aidants_connect_web.usager'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='duree_keyword',
            field=models.CharField(choices=[('SHORT', 'pour une durée de 1 jour'), ('LONG', 'pour une durée de 1 an'), ('EUS_03_20', 'jusqu’à la fin de l’état d’urgence sanitaire ')], max_length=16, null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Signé à distance ?'),
        ),
        migrations.RemoveField(
            model_name='autorisation',
            name='aidant',
        ),
        migrations.RemoveField(
            model_name='autorisation',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='autorisation',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='autorisation',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='autorisation',
            name='usager',
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='demarche',
            field=models.CharField(choices=[('papiers', 'Papiers - Citoyenneté'), ('famille', 'Famille'), ('social', 'Social - Santé'), ('travail', 'Travail'), ('logement', 'Logement'), ('transports', 'Transports'), ('argent', 'Argent'), ('justice', 'Justice'), ('etranger', 'Étranger'), ('loisirs', 'Loisirs')], max_length=16),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='revocation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de révocation'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('create_attestation', "Création d'une attestation"), ('create_autorisation', "Création d'une autorisation"), ('use_autorisation', "Utilisation d'une autorisation"), ('cancel_autorisation', "Révocation d'une autorisation")], max_length=30),
        ),
        migrations.AlterModelManagers(
            name='aidant',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='aidant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='usager_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='aidants_connect_web.usager'),
        ),
        migrations.RemoveField(
            model_name='journal',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='usager',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='usager_link',
            new_name='usager',
        ),
        migrations.AlterField(
            model_name='journal',
            name='aidant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelManagers(
            name='aidant',
            managers=[
                ('objects', aidants_connect_web.models.AidantManager()),
            ],
        ),
        migrations.AlterField(
            model_name='aidant',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
