# Generated by Django 2.2 on 2019-07-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandat',
            name='perimeter_other',
        ),
    ]
