# Generated by Django 2.2.3 on 2019-08-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0001_squashed_0003_auto_20190725_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='sub_usager',
        ),
        migrations.AddField(
            model_name='connection',
            name='usager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.Usager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisme',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.TextField(),
        ),
    ]
