# Generated by Django 3.1.1 on 2021-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0001_202101_stable_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarteTOTP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                ("seed", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
