# Generated by Django 2.2 on 2019-07-03 14:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0002_remove_mandat_perimeter_other'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandat',
            options={},
        ),
        migrations.RemoveField(
            model_name='connection',
            name='redirectUrl',
        ),
        migrations.AlterField(
            model_name='mandat',
            name='perimeter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
