# Generated by Django 3.2.13 on 2022-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0002_auto_20220511_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='duree_keyword',
            field=models.CharField(choices=[('SHORT', 'pour une durée de 1 jour'), ('MONTH', "pour une durée d'un mois (31 jours)"), ('SEMESTER', 'pour une durée de six mois (182 jours)'), ('LONG', 'pour une durée de 1 an'), ('EUS_03_20', 'jusqu’à la fin de l’état d’urgence sanitaire ')], max_length=16, null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='duree_keyword',
            field=models.CharField(choices=[('SHORT', 'pour une durée de 1 jour'), ('MONTH', "pour une durée d'un mois (31 jours)"), ('SEMESTER', 'pour une durée de six mois (182 jours)'), ('LONG', 'pour une durée de 1 an'), ('EUS_03_20', 'jusqu’à la fin de l’état d’urgence sanitaire ')], max_length=16, null=True, verbose_name='Durée'),
        ),
    ]
