# Generated by Django 2.2.3 on 2019-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0002_auto_20190722_1626")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organisme",
            field=models.TextField(default="No organisme"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.TextField(default="No profession"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="ville",
            field=models.TextField(default="No ville"),
            preserve_default=False,
        ),
    ]
