# Generated by Django 2.2 on 2019-06-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0003_auto_20190618_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandat',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='personal_data',
        ),
        migrations.AlterField(
            model_name='mandat',
            name='perimeter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.Demarche'),
        ),
    ]
