# Generated by Django 3.2.12 on 2022-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0003_auto_20220520_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE'),
        ),
    ]
