# Generated by Django 2.2 on 2019-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0004_auto_20190624_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemarcheCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
    ]
