# Generated by Django 2.2.4 on 2019-08-30 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0004_one_mandat_per_demarche")]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="demarches",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(default="No démarche"),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connection", name="duree", field=models.IntegerField(null=True)
        ),
    ]
