# Generated by Django 3.2.12 on 2022-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0004_organisation_codeinsee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='dep_codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code INSEE'),
        ),
    ]
