# Generated by Django 3.2.12 on 2022-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0005_organisation_dep_codeinsee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Commune Code INSEE'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='dep_codeinsee',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Département Code INSEE'),
        ),
    ]
