# Generated by Django 2.2 on 2019-06-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0006_demarche_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demarche',
            options={'ordering': ['category', '-weight']},
        ),
        migrations.AddField(
            model_name='mandat',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='demarchecategory',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='perimeter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.Demarche'),
        ),
    ]
