# Generated by Django 2.2.4 on 2019-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0006_auto_20190830_1846")]

    operations = [
        migrations.AddField(
            model_name="mandat",
            name="modified_by_access_token",
            field=models.TextField(default="No token provided"),
        )
    ]
