# Generated by Django 2.2.4 on 2019-10-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0007_mandat_modified_by_access_token")]

    operations = [
        migrations.AlterUniqueTogether(
            name="mandat", unique_together={("aidant", "demarche", "usager")}
        )
    ]
