# Generated by Django 2.2.4 on 2019-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0008_auto_20191021_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usager',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usager',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usager',
            name='preferred_contact_method',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
