# Generated by Django 3.2.15 on 2022-08-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0009_auto_20220822_1040'),
    ]

    operations = [
        migrations.DeleteModel(name='DatavizDepartment'),
        migrations.DeleteModel(name='DatavizDepartmentsToRegion'),
        migrations.DeleteModel(name='DatavizRegion'),
    ]
