# Generated by Django 2.2.4 on 2019-11-19 10:05
from datetime import timedelta
from django.db import migrations


def calculate_expiration_date_from_duree(apps, schema_editor):
    Mandat = apps.get_model("aidants_connect_web", "Mandat")
    for mandat in Mandat.objects.all():
        mandat.expiration_date = mandat.creation_date + timedelta(days=mandat.duree)
        mandat.save()


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0009_auto_20191119_1056")]

    operations = [migrations.RunPython(calculate_expiration_date_from_duree)]
