# Generated by Django 2.2.4 on 2019-11-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0010_auto_20191119_1105")]

    operations = [migrations.RemoveField(model_name="mandat", name="duree")]
