# Generated by Django 2.2.8 on 2019-12-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("aidants_connect_web", "0011_remove_mandat_duree")]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="No name provided")),
                ("siret", models.PositiveIntegerField(default=1)),
                ("address", models.TextField(default="No address provided")),
            ],
        ),
        migrations.AddField(
            model_name="aidant",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aidants_connect_web.Organisation",
            ),
        ),
        migrations.RemoveField(model_name="aidant", name="organisme"),
        migrations.RemoveField(model_name="aidant", name="ville"),
    ]
