# Generated by Django 3.0.2 on 2020-02-10 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0012_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandat",
            name="last_used_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="journal",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect_aidant", "Connexion d'un aidant"),
                    ("activity_check_aidant", "Reprise de connexion d'un aidant"),
                    ("create_mandat", "Création d'un mandat"),
                    ("use_mandat", "Utilisation d'un mandat"),
                    ("update_mandat", "Renouvellement d'un mandat"),
                ],
                max_length=30,
            ),
        ),
    ]
