# Generated by Django 3.0.2 on 2020-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0012_organisations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect_aidant", "Connexion d'un aidant"),
                    ("create_mandat", "Création d'un mandat"),
                    ("use_mandat", "Utilisation d'un mandat"),
                    ("update_mandat", "Modification d'un mandat"),
                ],
                max_length=30,
            ),
        ),
    ]
