# Generated by Django 3.2.14 on 2022-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0012_habilitationrequest_date_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='aidant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='habilitationrequest',
            name='formation_done',
            field=models.BooleanField(default=False, verbose_name='Formation faite'),
        ),
    ]
