# Generated by Django 3.0.2 on 2020-02-06 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0012_organisations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="action",
            field=models.CharField(
                choices=[
                    ("connect_aidant", "Connexion d'un aidant"),
                    ("activity_check_aidant", "Reprise de connexion d'un aidant"),
                    ("create_mandat", "Création d'un mandat"),
                    ("use_mandat", "Utilisation d'un mandat"),
                    ("update_mandat", "Renouvellement d'un mandat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="usager",
            name="birthplace",
            field=models.PositiveIntegerField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(9999),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usager",
            name="birthplace",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="usager",
            name="birthplace",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
