# Generated by Django 3.0.2 on 2020-01-23 16:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0012_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="hash_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
