# Generated by Django 3.0.2 on 2020-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0013_journal_hash_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="journal", name="hash_data",),
        migrations.AddField(
            model_name="journal",
            name="mandat_print_hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
