# Generated by Django 3.0.3 on 2020-02-19 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0014_auto_20200213_1706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usager", options={"ordering": ["family_name", "given_name"]},
        ),
        migrations.AlterField(
            model_name="aidant",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aidants",
                to="aidants_connect_web.Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="aidant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usagers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="mandat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usagers",
                to="aidants_connect_web.Mandat",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="usager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usagers",
                to="aidants_connect_web.Usager",
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="aidant",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="usager",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandats",
                to="aidants_connect_web.Usager",
            ),
        ),
    ]
