# Generated by Django 4.0.8 on 2023-01-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0015_connection_remote_constent_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitationrequest',
            name='origin',
            field=models.CharField(choices=[('datapass', 'Datapass'), ('responsable', 'Responsable Structure'), ('autre', 'Autre'), ('habilitation', 'Formulaire Habilitation')], default='autre', max_length=150, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='status',
            field=models.CharField(choices=[('habilitation_waitling_list', "Liste d'attente demande habilitation"), ('new', 'Nouvelle'), ('processing', 'En cours'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='habilitation_waitling_list', max_length=150, verbose_name='État'),
        ),
    ]
