# Generated by Django 3.0.3 on 2020-02-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0015_add_ordering_and_related_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection", old_name="expiresOn", new_name="expires_on",
        ),
    ]
