# Generated by Django 4.1.5 on 2023-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0016_alter_habilitationrequest_origin_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action__in', ['remote_mandat_consent_sent', 'remote_mandat_consent_received', 'remote_mandat_denial_received']), _negated=True), models.Q(('aidant__isnull', False), ('is_remote_mandat', True), ('user_phone__isnull_or_blank', False), ('consent_request_id__isnull_or_blank', False), ('additional_information__isnull_or_blank', False)), _connector='OR'), name='infos_set_remote_mandate_by_sms'),
        ),
    ]
