# Generated by Django 4.0.9 on 2023-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0017_journal_infos_set_remote_mandate_by_sms"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="journal",
            name="infos_set_remote_mandate_by_sms",
        ),
        migrations.AddConstraint(
            model_name="journal",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        (
                            "action__in",
                            [
                                "remote_mandat_consent_sent",
                                "remote_mandat_consent_received",
                                "remote_mandat_denial_received",
                            ],
                        ),
                        _negated=True,
                    ),
                    models.Q(
                        ("aidant__isnull", False),
                        ("is_remote_mandat", True),
                        ("user_phone__isnull_or_blank", False),
                        ("consent_request_id__isnull_or_blank", False),
                        ("remote_constent_method", "SMS"),
                        ("additional_information__isnull_or_blank", False),
                    ),
                    _connector="OR",
                ),
                name="infos_set_remote_mandate_by_sms",
            ),
        ),
    ]
