# Generated by Django 4.0.10 on 2023-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0018_remove_journal_infos_set_remote_mandate_by_sms_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journal',
            name='infos_set_remote_mandate_by_sms',
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('card_association', "Association d'une carte à d'un aidant"), ('card_validation', "Validation d'une carte associée à un aidant"), ('card_dissociation', "Séparation d'une carte et d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('update_phone_usager', "Le téléphone de l'usager a été modifié"), ('create_attestation', "Création d'une attestation"), ('create_autorisation', "Création d'une autorisation"), ('use_autorisation', "Utilisation d'une autorisation"), ('cancel_autorisation', "Révocation d'une autorisation"), ('cancel_mandat', "Révocation d'un mandat"), ('import_totp_cards', 'Importation de cartes TOTP'), ('init_renew_mandat', "Lancement d'une procédure de renouvellement"), ('transfer_mandat', 'Transférer un mandat à une autre organisation'), ('switch_organisation', "Changement d'organisation"), ('remote_sms_consent_received', 'Consentement reçu pour un mandat conclu par SMS'), ('remote_sms_denial_received', 'Refus reçu pour un mandat conclu par SMS'), ('remote_sms_consent_sent', 'Demande de consentement pour un mandat conclu par SMS envoyé'), ('remote_sms_recap_sent', 'Récapitulatif préalable pour mandat conclu par SMS envoyé')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action__in', ['remote_sms_consent_sent', 'remote_sms_consent_received', 'remote_sms_denial_received', 'remote_sms_recap_sent']), _negated=True), models.Q(('aidant__isnull', False), ('is_remote_mandat', True), ('user_phone__isnull_or_blank', False), ('consent_request_id__isnull_or_blank', False), ('remote_constent_method', 'SMS'), ('additional_information__isnull_or_blank', False)), _connector='OR'), name='infos_set_remote_mandate_by_sms'),
        ),
    ]
