# Generated by Django 4.0.8 on 2023-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0018_remove_journal_infos_set_remote_mandate_by_sms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidantStatistiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('number_aidants', models.PositiveIntegerField(default=0, verbose_name="Nb d'aidant")),
                ('number_responsable', models.PositiveIntegerField(default=0, verbose_name='Nb de responsable')),
                ('number_aidant_can_create_mandat', models.PositiveIntegerField(default=0, verbose_name="Nb d'aidant pouvant créer des mandats")),
                ('number_aidant_with_login', models.PositiveIntegerField(default=0, verbose_name="Nb d'aidant pouvant créer des mandats et s'étant connecté")),
                ('number_aidant_who_have_created_mandat', models.PositiveIntegerField(default=0, verbose_name="Nb d'aidant qui ont créé des mandats")),
                ('number_aidants_is_active',
                models.PositiveIntegerField(default=0, verbose_name="Nb d'aidant 'actif au sens django' ")),
                ('number_aidants_without_totp',
                 models.PositiveIntegerField(default=0, verbose_name="Nb d'aidant sans carte TOTP ")
                 )
            ],
        ),
    ]
