# Generated by Django 4.0.8 on 2023-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0019_aidantstatistiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartetotp',
            name='is_functional',
            field=models.BooleanField(default=True, verbose_name='Fonctionne correctement'),
        ),
    ]
