# Generated by Django 3.0.5 on 2020-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0020_journal_action_add_update_email_usager"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="additional_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mandat",
            name="is_remote_mandat",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(model_name="connection", name="duree",),
        migrations.AddField(
            model_name="connection",
            name="duree_keyword",
            field=models.CharField(
                choices=[
                    ("SHORT", "pour une durée de 1 jour"),
                    ("LONG", "pour une durée de 1 an"),
                    (
                        "EUS_03_20",
                        "jusqu’à la fin de l’état d’urgence sanitaire déclaré par l’article 4 de la loi du 23 mars 2020.",
                    ),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="is_remote_mandat",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterModelOptions(
            name="connection", options={"verbose_name": "connexion"},
        ),
        migrations.AlterModelOptions(
            name="journal",
            options={
                "verbose_name": "entrée de journal",
                "verbose_name_plural": "entrées de journal",
            },
        ),
        migrations.AlterField(
            model_name="journal",
            name="is_remote_mandat",
            field=models.BooleanField(default=False),
        ),
    ]
