# Generated by Django 4.0.8 on 2023-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0020_cartetotp_is_functional'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='france_services_label',
            field=models.BooleanField(default=False, verbose_name='Labellisation France Services'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='france_services_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Numéro d’immatriculation France Services'),
        ),
    ]
