# Generated by Django 3.0.5 on 2020-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0021_remote_mandat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="duree_keyword",
            field=models.CharField(
                choices=[
                    ("SHORT", "pour une durée de 1 jour"),
                    ("LONG", "pour une durée de 1 an"),
                    ("EUS_03_20", "jusqu’à la fin de l’état d’urgence sanitaire "),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
