# Generated by Django 3.0.3 on 2020-04-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0022_migrate_mandats_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandat',
            name='aidant',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='demarche',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='last_mandat_renewal_date',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='last_mandat_renewal_token',
        ),
    ]
