# Generated by Django 3.0.5 on 2020-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0022_auto_20200417_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='is_remote_mandat',
            field=models.BooleanField(default=False),
        ),
    ]
