# Generated by Django 3.0.3 on 2020-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0023_remove_obsolete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='access_token',
            field=models.TextField(default='No token provided'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='nonce',
            field=models.TextField(default='No nonce provided'),
        ),
    ]
