# Generated by Django 4.2 on 2023-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0024_alter_aidantstatistiques_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitationrequest',
            name='status',
            field=models.CharField(choices=[('habilitation_waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'En cours'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='habilitation_waitling_list', max_length=150, verbose_name='État'),
        ),
    ]
