# Generated by Django 4.2 on 2023-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0025_alter_habilitationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorisation',
            name='demarche',
            field=models.CharField(choices=[('papiers', 'Papiers - Citoyenneté - Élections'), ('famille', 'Famille - Scolarité'), ('social', 'Social - Santé'), ('travail', 'Travail - Formation'), ('logement', 'Logement'), ('transports', 'Transports - Mobilité'), ('argent', 'Argent - Impôts - Consomation'), ('justice', 'Justice'), ('etranger', 'Étranger - Europe'), ('loisirs', 'Loisirs - Sport - Culture')], max_length=16),
        ),
    ]
