# Generated by Django 4.2 on 2023-05-05 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0026_alter_autorisation_demarche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[])),
                ('date', models.DateField(auto_now_add=True)),
                ('must_ack', models.BooleanField(default=True, verbose_name='Doit être acquité pour disparaître')),
                ('auto_ack_date', models.DateField(default=None, null=True, verbose_name='Échéance')),
                ('was_ack', models.BooleanField(default=False, null=True, verbose_name='A été acquité')),
                ('aidant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('must_ack', False), ('was_ack__isnull', False), _connector='XOR'), models.Q(('auto_ack_date__isnull', False), ('was_ack__isnull', False), _connector='OR')), name='must_ack_conditions'),
        ),
    ]
