# Generated by Django 3.0.5 on 2020-05-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0026_rename_mandat_step2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorisation",
            name="aidant",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorisations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="autorisation",
            name="usager",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorisations",
                to="aidants_connect_web.Usager",
            ),
        ),
        migrations.RenameField(
            model_name="autorisation",
            old_name="last_mandat_renewal_date",
            new_name="last_renewal_date",
        ),
        migrations.RenameField(
            model_name="autorisation",
            old_name="last_mandat_renewal_token",
            new_name="last_renewal_token",
        ),
    ]
