# Generated by Django 3.0.5 on 2020-05-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0027_rename_mandat_step3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="autorisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usagers",
                to="aidants_connect_web.Autorisation",
            ),
        ),
    ]
