# Generated by Django 4.2.1 on 2023-05-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0028_aidantstatistiques_number_future_aidant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Contenu de la notification'),
        ),
    ]
