# Generated by Django 3.0.5 on 2020-05-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0028_rename_mandat_step4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="aidant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="autorisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="aidants_connect_web.Autorisation",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="usager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="aidants_connect_web.Usager",
            ),
        ),
    ]
