# Generated by Django 4.2.1 on 2023-05-26 08:38

import uuid

from django.db import migrations, models


def gen_uuid(apps, _):
    Organisation = apps.get_model("aidants_connect_web", "Organisation")
    for row in Organisation.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("aidants_connect_web", "0029_notification_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=False, verbose_name="API ID"
            ),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="API ID"
            ),
        ),
    ]
