# Generated by Django 3.0.5 on 2020-05-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0029_fix_related_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autorisation",
            old_name="is_remote_mandat",
            new_name="is_remote",
        ),
    ]
