# Generated by Django 4.2.1 on 2023-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0030_organisation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='deactivation_warning_at',
            field=models.DateTimeField(default=None, null=True, verbose_name="Date d'envoi de l’email d’alerte de désactivation"),
        ),
    ]
