# Generated by Django 3.0.5 on 2020-06-01 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0030_rename_is_remote_mandat_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorisation",
            name="aidant",
            field=models.ForeignKey(
                db_index=False,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorisations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="autorisation",
            name="usager",
            field=models.ForeignKey(
                db_index=False,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorisations",
                to="aidants_connect_web.Usager",
            ),
        ),
    ]
