# Generated by Django 4.2.2 on 2023-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0031_aidant_deactivation_warning_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='ff_otp_app',
            field=models.BooleanField(default=False, verbose_name='Le responsable peut ajouter une application OTP aux aidants de son organisation'),
        ),
    ]
