# Generated by Django 4.2.2 on 2023-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0032_aidant_ff_otp_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidantstatistiques',
            name='number_aidants_in_zrr',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant travaillant dans des stuctures classées en zone de revitalisation rurale"),
        ),
        migrations.AddField(
            model_name='aidantstatistiques',
            name='number_orgas_in_zrr',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de structures classées en zone de revitalisation rurale'),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbydepartment',
            name='number_aidants_in_zrr',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant travaillant dans des stuctures classées en zone de revitalisation rurale"),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbydepartment',
            name='number_orgas_in_zrr',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de structures classées en zone de revitalisation rurale'),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbyregion',
            name='number_aidants_in_zrr',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant travaillant dans des stuctures classées en zone de revitalisation rurale"),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbyregion',
            name='number_orgas_in_zrr',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de structures classées en zone de revitalisation rurale'),
        ),
    ]
