# Generated by Django 3.0.7 on 2020-06-19 17:37

import aidants_connect_web.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0033_add_new_mandat_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandat",
            name="organisation",
            field=models.ForeignKey(
                default=aidants_connect_web.models.get_staff_organisation_name_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandats",
                to="aidants_connect_web.Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="usager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mandats",
                to="aidants_connect_web.Usager",
            ),
        ),
    ]
