# Generated by Django 4.2.3 on 2023-07-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0034_alter_aidant_ff_otp_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidantstatistiques',
            name='number_old_aidants_warned',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant actifs qui ne se sont pas connectés depuis longtemps et qui ont été alertés"),
        ),
        migrations.AddField(
            model_name='aidantstatistiques',
            name='number_old_inactive_aidants_warned',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant inactifs qui ne se sont pas connectés depuis longtemps et qui ont été alertés"),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbydepartment',
            name='number_old_aidants_warned',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant actifs qui ne se sont pas connectés depuis longtemps et qui ont été alertés"),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbydepartment',
            name='number_old_inactive_aidants_warned',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant inactifs qui ne se sont pas connectés depuis longtemps et qui ont été alertés"),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbyregion',
            name='number_old_aidants_warned',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant actifs qui ne se sont pas connectés depuis longtemps et qui ont été alertés"),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbyregion',
            name='number_old_inactive_aidants_warned',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'aidant inactifs qui ne se sont pas connectés depuis longtemps et qui ont été alertés"),
        ),
    ]
