# Generated by Django 4.2.3 on 2023-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0035_aidantstatistiques_number_old_aidants_warned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitationrequest',
            name='status',
            field=models.CharField(choices=[('habilitation_waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'En cours'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='habilitation_waitling_list', max_length=150, verbose_name='État'),
        ),
    ]
