# Generated by Django 3.0.4 on 2020-06-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0035_add_autorisation_revocation_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="autorisation", name="last_renewal_date",),
    ]
