# Generated by Django 3.0.5 on 2020-06-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0036_remove_autorisation_last_renewal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandat",
            name="usager",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandats",
                to="aidants_connect_web.Usager",
            ),
        ),
    ]
