# Generated by Django 4.2.6 on 2023-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0037_cartetotp_totp_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='auto_ack_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Échéance'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INFORMATION', 'Information'), ('NEW_FEATURE', 'Nouveauté sur Aidants Connect'), ('WARNING', 'Alerte')]),
        ),
    ]
