# Generated by Django 3.0.7 on 2020-06-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0037_auto_20200605_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="address",
            field=models.TextField(
                default="No address provided", verbose_name="Adresse"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.TextField(default="No name provided", verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="siret",
            field=models.PositiveIntegerField(default=1, verbose_name="N° SIRET"),
        ),
        migrations.AlterField(
            model_name="usager",
            name="given_name",
            field=models.CharField(max_length=255, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="usager",
            name="family_name",
            field=models.CharField(max_length=255, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="usager",
            name="preferred_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="usager",
            name="gender",
            field=models.CharField(
                choices=[("female", "Femme"), ("male", "Homme")],
                default="female",
                max_length=6,
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="usager",
            name="birthdate",
            field=models.DateField(verbose_name="Date de naissance"),
        ),
        migrations.AlterField(
            model_name="usager",
            name="birthplace",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="usager",
            name="birthcountry",
            field=models.CharField(
                default="99100", max_length=5, verbose_name="Pays de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="usager",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="usager",
            field=models.ForeignKey(
                to="aidants_connect_web.Usager",
                related_name="mandats",
                on_delete=django.db.models.deletion.PROTECT,
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="expiration_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date d'expiration"
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="duree_keyword",
            field=models.CharField(
                choices=[
                    ("SHORT", "pour une durée de 1 jour"),
                    ("LONG", "pour une durée de 1 an"),
                    ("EUS_03_20", "jusqu’à la fin de l’état d’urgence sanitaire "),
                ],
                max_length=16,
                null=True,
                verbose_name="Durée",
            ),
        ),
        migrations.AlterField(
            model_name="mandat",
            name="is_remote",
            field=models.BooleanField(default=False, verbose_name="Signé à distance ?"),
        ),
        migrations.RemoveField(model_name="autorisation", name="aidant",),
        migrations.RemoveField(model_name="autorisation", name="creation_date",),
        migrations.RemoveField(model_name="autorisation", name="expiration_date",),
        migrations.RemoveField(model_name="autorisation", name="is_remote",),
        migrations.RemoveField(model_name="autorisation", name="usager",),
        migrations.AlterField(
            model_name="autorisation",
            name="demarche",
            field=models.CharField(
                max_length=16,
                choices=[
                    ("papiers", "Papiers - Citoyenneté"),
                    ("famille", "Famille"),
                    ("social", "Social - Santé"),
                    ("travail", "Travail"),
                    ("logement", "Logement"),
                    ("transports", "Transports"),
                    ("argent", "Argent"),
                    ("justice", "Justice"),
                    ("etranger", "Étranger"),
                    ("loisirs", "Loisirs"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="autorisation",
            name="revocation_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de révocation"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="action",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("connect_aidant", "Connexion d'un aidant"),
                    ("activity_check_aidant", "Reprise de connexion d'un aidant"),
                    ("franceconnect_usager", "FranceConnexion d'un usager"),
                    ("update_email_usager", "L'email de l'usager a été modifié"),
                    ("create_attestation", "Création d'une attestation"),
                    ("create_autorisation", "Création d'une autorisation"),
                    ("use_autorisation", "Utilisation d'une autorisation"),
                    ("cancel_autorisation", "Révocation d'une autorisation"),
                ],
            ),
        ),
    ]
