# Generated by Django 3.0.7 on 2020-09-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0038_post_migration_cleanup"),
    ]

    operations = [
        migrations.AlterModelManagers(name="aidant", managers=[],),
        migrations.AddField(
            model_name="journal",
            name="aidant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="usager_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="aidants_connect_web.Usager",
            ),
        ),
    ]
