# Generated by Django 4.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0039_organisation_created_at_organisation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='legal_cat_level_one',
            field=models.CharField(max_length=255, null=True, verbose_name='Niveau I catégories juridiques'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='legal_cat_level_three',
            field=models.CharField(max_length=255, null=True, verbose_name='Niveau III catégories juridiques'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='legal_cat_level_two',
            field=models.CharField(max_length=255, null=True, verbose_name='Niveau II catégories juridiques'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='legal_category',
            field=models.PositiveIntegerField(default=0, verbose_name='categorieJuridiqueUniteLegale'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='siren',
            field=models.BigIntegerField(default=1, verbose_name='N° SIREN'),
        ),
    ]
