# Generated by Django 3.0.7 on 2020-09-01 13:52

from django.db import migrations


def migrate_journal_aidant_and_usager(apps, schema_editor):
    # Mandat = apps.get_model("aidants_connect_web", "Mandat")
    # for mandat in Mandat.objects.all():
    #     mandat.expiration_date = mandat.creation_date + timedelta(days=mandat.duree)
    #     mandat.save()
    Aidant = apps.get_model("aidants_connect_web", "Aidant")
    Usager = apps.get_model("aidants_connect_web", "Usager")
    Journal = apps.get_model("aidants_connect_web", "Journal")
    for journal in Journal.objects.all():
        # initiator --> aidant
        if journal.initiator:
            try:
                journal_aidant_email = journal.initiator.split(" - ")[2]
                journal.aidant = Aidant.objects.get(email=journal_aidant_email)
            except (IndexError, ValueError):
                print("Journal initiator/aidant error", journal.__dict__)
        # usager --> usager_link
        if journal.usager:
            try:
                journal_usager_id = journal.usager.split(" - ")[1]
                journal.usager_link = Usager.objects.get(pk=journal_usager_id)
            except (IndexError, ValueError):
                print("Journal usager/usager_link error", journal.__dict__)
        # save
        journal.save()


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0039_journal_add_foreign_keys"),
    ]

    operations = [migrations.RunPython(migrate_journal_aidant_and_usager)]
