# Generated by Django 3.0.7 on 2020-09-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0040_journal_migrate_aidant_and_usager"),
    ]

    operations = [
        migrations.RemoveField(model_name="journal", name="initiator",),
        migrations.RemoveField(model_name="journal", name="usager",),
    ]
