# Generated by Django 4.2.6 on 2023-10-23 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0041_alter_notification_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReboardingAidantStatistiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('warning_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date de l'envoie de l'alerte")),
                ('reboarding_session_date', models.DateField(verbose_name='Date de la session de réembarquement')),
                ('connexions_before_reboarding', models.PositiveIntegerField(verbose_name='Nb connexion avant réembarquement')),
                ('connexions_j30_after', models.PositiveIntegerField(verbose_name='Nb connexion J30 après réembarquement')),
                ('connexions_j90_after', models.PositiveIntegerField(verbose_name='Nb connexion J90 après réembarquement')),
                ('created_mandats_before_reboarding', models.PositiveIntegerField(verbose_name='Nb mandats créés avant réembarquement')),
                ('created_mandats_j30_after', models.PositiveIntegerField(verbose_name='Nb mandats créés J30 après réembarquement')),
                ('created_mandats_j90_after', models.PositiveIntegerField(verbose_name='Nb mandats créés J90 après réembarquement')),
                ('demarches_before_reboarding', models.PositiveIntegerField(verbose_name='Nb démarches avant réembarquement')),
                ('demarches_j30_after', models.PositiveIntegerField(verbose_name='Nb démarches J30 après réembarquement')),
                ('demarches_j90_after', models.PositiveIntegerField(verbose_name='Nb démarches J90 après réembarquement')),
                ('usagers_before_reboarding', models.PositiveIntegerField(verbose_name='Nb usagers accompagnés avant réembarquement')),
                ('usagers_j30_after', models.PositiveIntegerField(verbose_name='Nb usagers accompagnés J30 après réembarquement')),
                ('usagers_j90_after', models.PositiveIntegerField(verbose_name='Nb usagers accompagnés J90 après réembarquement')),
                ('aidant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aidant')),
            ],
        ),
    ]
