# Generated by Django 3.0.7 on 2020-09-01 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0041_journal_remove_initiator_and_usager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal", old_name="usager_link", new_name="usager",
        ),
        migrations.AlterField(
            model_name="journal",
            name="aidant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
