# Generated by Django 3.0.7 on 2020-11-18 15:01

import aidants_connect_web.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0042_journal_rename_usager"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="aidant",
            managers=[("objects", aidants_connect_web.models.AidantManager()),],
        ),
    ]
