# Generated by Django 4.2.7 on 2023-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0042_reboardingaidantstatistiques'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='must_ack_conditions',
        ),
        migrations.AlterField(
            model_name='notification',
            name='was_ack',
            field=models.BooleanField(default=False, verbose_name='A été acquité'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('must_ack', False), ('was_ack', True), _negated=True), models.Q(('auto_ack_date__isnull', False), ('must_ack', True), _connector='XOR')), name='must_ack_conditions'),
        ),
    ]
