# Generated by Django 3.1.1 on 2021-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0043_auto_20201118_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidant',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
