# Generated by Django 4.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0043_remove_notification_must_ack_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='connexions_before_reboarding',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb connexion avant réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='connexions_j30_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb connexion J30 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='connexions_j90_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb connexion J90 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='created_mandats_before_reboarding',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb mandats créés avant réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='created_mandats_j30_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb mandats créés J30 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='created_mandats_j90_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb mandats créés J90 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='demarches_before_reboarding',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb démarches avant réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='demarches_j30_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb démarches J30 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='demarches_j90_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb démarches J90 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='usagers_before_reboarding',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb usagers accompagnés avant réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='usagers_j30_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb usagers accompagnés J30 après réembarquement'),
        ),
        migrations.AlterField(
            model_name='reboardingaidantstatistiques',
            name='usagers_j90_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb usagers accompagnés J90 après réembarquement'),
        ),
    ]
