# Generated by Django 3.1.1 on 2020-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0043_auto_20201118_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidant",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="siret",
            field=models.BigIntegerField(default=1, verbose_name="N° SIRET"),
        ),
    ]
