# Generated by Django 4.2.6 on 2023-11-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0044_add_default_in_reboarding_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidant',
            name='ff_otp_app',
        ),
    ]
