# Generated by Django 3.1.1 on 2021-02-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0044_auto_20201216_1047"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="mandat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="aidants_connect_web.mandat",
            ),
        ),
    ]
