# Generated by Django 3.1.1 on 2021-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0045_journal_mandat"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="zipcode",
            field=models.CharField(
                default="0", max_length=10, verbose_name="Code Postal"
            ),
        ),
    ]
