# Generated by Django 4.2.8 on 2023-12-07 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aidants_connect_web.models.other_models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0045_remove_aidant_ff_otp_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(default=aidants_connect_web.models.other_models._filepath_generator, max_length=40)),
                ('state', models.IntegerField(choices=[(1, 'Ongoing'), (2, 'Done'), (3, 'Error')], default=1)),
                ('aidant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
