# Generated by Django 4.2.8 on 2024-01-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0047_alter_autorisation_demarche'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='activity_tracking_warning_at',
            field=models.DateTimeField(default=None, null=True, verbose_name="Date d'envoi de l’email de suivi utilisation du service"),
        ),
    ]
