# Generated by Django 3.1.1 on 2021-03-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0048_auto_20210318_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350, verbose_name="Nom")),
            ],
        ),
        migrations.AddField(
            model_name="organisation",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aidants_connect_web.organisationtype",
            ),
        ),
    ]
