# Generated by Django 4.2.9 on 2024-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0048_aidant_activity_tracking_warning_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='state',
            field=models.IntegerField(choices=[(1, 'En cours'), (2, 'Fini'), (3, 'Erreur')], default=1, verbose_name='État'),
        ),
    ]
