# Generated by Django 3.1.1 on 2021-03-21 20:54

from django.db import migrations

orga_types = [
    "France Services/MSAP",
    "CCAS",
    "Centres sociaux",
    "Sécrétariats de mairie",
    "Maisons départementales des solidarités",
    "Médiathèque",
    "Autre guichet d’accueil de service public de proximité",
    "Guichet d’accueil d’opérateur de service public (CAF, Pôle Emploi, etc.)",
    "Autres associations d’accompagnement des publics ou de médiation numérique",
    "Structure médico-sociale (CSAPA, CHU, CMS)",
    "Indépendant",
    "Autre",
]


def add_organisation_types(apps, schema_editor):
    OrganisationType = apps.get_model("aidants_connect_web", "OrganisationType")
    for one_type in orga_types:
        OrganisationType.objects.get_or_create(name=one_type)


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0049_auto_20210321_2152"),
    ]

    operations = [
        migrations.RunPython(add_organisation_types),
    ]
