# Generated by Django 4.2.9 on 2024-02-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0050_aidantstatistiques_number_aidants_with_otp_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='task_uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
