# Generated by Django 4.2.9 on 2024-02-05 14:05
from typing import Type

import django.db.models.deletion
from django.db import migrations, models


def migrate_habilitationrequest_status(apps, _):
    HabilitationRequest = apps.get_model("aidants_connect_web", "HabilitationRequest")
    HabilitationRequest.objects.filter(status="habilitation_waitling_list").update(status="waitling_list")


def unmigrate_habilitationrequest_status(apps, _):
    HabilitationRequest = apps.get_model("aidants_connect_web", "HabilitationRequest")
    HabilitationRequest.objects.filter(status="waitling_list").update(status="habilitation_waitling_list")


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0051_exportrequest_task_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoReferentNonAidantRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('profession', models.CharField(max_length=150, verbose_name='Profession')),
                ('email', models.EmailField(max_length=150, verbose_name='Email professionnel')),
                ('status', models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'En cours'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État'),),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
        ),
        migrations.AddField(
            model_name='aidant',
            name='referent_non_aidant',
            field=models.BooleanField(default=False, help_text="Ne pas pas accéder à l'espace Aidant. Ce champ est incompatible avec le champ «\xa0Aidant - Peut créer des mandats\xa0»", verbose_name='Référent non-aidant - Ne peut pas créer de mandat'),
        ),
        migrations.AddConstraint(
            model_name='aidant',
            constraint=models.CheckConstraint(check=models.Q(('referent_non_aidant', False), models.Q(('can_create_mandats', False), ('referent_non_aidant', True)), _connector='OR'), name='referent_non_aidant_and_can_create_mandats_incompatible'),
        ),
        migrations.AddField(
            model_name='coreferentnonaidantrequest',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_referent_validation_requests', to='aidants_connect_web.organisation'),
        ),
        migrations.RunPython(
            migrate_habilitationrequest_status, reverse_code=unmigrate_habilitationrequest_status
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='status',
            field=models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'En cours'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État'),
        ),
    ]
