# Generated by Django 3.1.6 on 2021-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0052_add_departements_to_region_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidant",
            name="can_create_mandats",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aidant",
            name="responsable_de",
            field=models.ManyToManyField(
                related_name="responsables", to="aidants_connect_web.Organisation"
            ),
        ),
    ]
