# Generated by Django 3.1.6 on 2021-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0052_add_departements_to_region_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidant",
            name="responsable_de",
            field=models.ManyToManyField(
                null=True,
                related_name="responsables",
                to="aidants_connect_web.Organisation",
            ),
        ),
    ]
