# Generated by Django 4.2.10 on 2024-02-13 15:19

import django.contrib.postgres.fields
from django.db import migrations, models

import aidants_connect_web.models.organisation


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0053_userfingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='allowed_demarches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('papiers', 'Papiers - Citoyenneté - Élections'), ('famille', 'Famille - Scolarité'), ('social', 'Social - Santé'), ('travail', 'Travail - Formation'), ('logement', 'Logement'), ('transports', 'Transports - Mobilité'), ('argent', 'Argent - Impôts - Consommation'), ('justice', 'Justice'), ('etranger', 'Étranger - Europe'), ('loisirs', 'Loisirs - Sport - Culture')], max_length=16), default=aidants_connect_web.models.organisation.organisation_allowed_demarches, size=None),
        ),
    ]
