# Generated by Django 4.2.10 on 2024-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0054_organisation_allowed_demarches'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='conseiller_numerique',
            field=models.BooleanField(default=False, verbose_name="L'aidant est conseiller numérique"),
        ),
    ]
