# Generated by Django 3.1.8 on 2021-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0054_usager_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidant",
            name="responsable_de",
            field=models.ManyToManyField(
                blank=True,
                related_name="responsables",
                to="aidants_connect_web.Organisation",
            ),
        ),
    ]
