# Generated by Django 4.2.10 on 2024-02-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0055_aidant_conseiller_numerique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Type de formation aidant',
                'verbose_name_plural': 'Types de formation aidant',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Date et heure de début de la formation')),
                ('end_datetime', models.DateTimeField(verbose_name='Date et heure de fin de la formation')),
                ('duration', models.IntegerField(verbose_name='Durée en heures')),
                ('max_attendants', models.IntegerField(verbose_name="Nombre maximum d'inscrits possibles")),
                ('status', models.IntegerField(choices=[(1, 'En présentiel'), (2, 'À distance')], verbose_name='En présentiel/à distance')),
                ('place', models.CharField(max_length=500, verbose_name='Lieu')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidants_connect_web.formationtype')),
            ],
            options={
                'verbose_name': 'Formation aidant',
                'verbose_name_plural': 'Formations aidant',
            },
        ),
    ]
