# Generated by Django 4.2.10 on 2024-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0057_formationattendant_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='IdGenerator',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='idgenerator',
                    table='aidants_connect_common_idgenerator',
                ),
            ]
        ),
        migrations.AlterUniqueTogether(
            name='formationattendant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='formationattendant',
            name='attendant_content_type',
        ),
        migrations.RemoveField(
            model_name='formationattendant',
            name='formation',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='FormationAttendant',
        ),
        migrations.DeleteModel(
            name='FormationType',
        ),
    ]
