# Generated by Django 4.2.10 on 2024-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0058_alter_formationattendant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitationrequest',
            name='conseiller_numerique',
            field=models.BooleanField(default=False, verbose_name='Est un conseiller numérique'),
        ),
    ]
