# Generated by Django 4.2.10 on 2024-03-12 13:28

from django.db import migrations

import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0058_alter_formationattendant_unique_together_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='habilitationrequest',
            trigger=pgtrigger.compiler.Trigger(name='check_attendants_count', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE attendants_count INTEGER;', func="-- Prevent concurrent inserts from multiple transactions\nLOCK TABLE aidants_connect_web_habilitationrequest IN EXCLUSIVE MODE;\n\nUPDATE aidants_connect_common_formationattendant fa\nSET attendant_id = NEW.id, attendant_content_type_id = ct1.id\nFROM django_content_type ct1\nINNER JOIN aidants_connect_habilitation_aidantrequest ar\nON LOWER(ar.email) = LOWER(NEW.email)\nINNER JOIN django_content_type ct2\nON ct2.app_label = 'aidants_connect_habilitation'\nAND ct2.model = 'aidantrequest'\nWHERE ct1.app_label = 'aidants_connect_web'\nAND ct1.model = 'habilitationrequest'\nAND fa.attendant_id = ar.id\nAND fa.attendant_content_type_id = ct2.id;\n\nRETURN NEW;", hash='44972ca756d127d2623c73c095198abd0a5371b7', operation='INSERT', pgid='pgtrigger_check_attendants_count_d02b7', table='aidants_connect_web_habilitationrequest', when='AFTER')),
        ),
    ]
