# Generated by Django 3.1.12 on 2021-07-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0061_auto_20210706_1439"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabilitationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "Une demande a déjà été déposée pour cette adresse e-mail."
                        },
                        max_length=150,
                    ),
                ),
                ("profession", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("validated", "Validée"),
                            ("processing", "En cours"),
                            ("refused", "Refusée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="processing",
                        max_length=150,
                        verbose_name="État",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilitation_requests",
                        to="aidants_connect_web.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande d’habilitation",
                "verbose_name_plural": "demandes d’habilitation",
            },
        ),
        migrations.AddConstraint(
            model_name="habilitationrequest",
            constraint=models.UniqueConstraint(
                fields=("email", "organisation"), name="unique_email_per_orga"
            ),
        ),
    ]
