# Generated by Django 3.1.12 on 2021-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0061_auto_20210706_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usager",
            name="preferred_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
