# Generated by Django 3.1.12 on 2021-08-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0062_auto_20210720_1142"),
        ("aidants_connect_web", "0062_auto_20210712_1644"),
    ]

    operations = []
