# Generated by Django 4.2.11 on 2024-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0062_referentsformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidantstatistiques',
            name='revoked_mandats',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb mandats révoqués'),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbydepartment',
            name='revoked_mandats',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb mandats révoqués'),
        ),
        migrations.AddField(
            model_name='aidantstatistiquesbyregion',
            name='revoked_mandats',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb mandats révoqués'),
        ),
    ]
