# Generated by Django 4.2.11 on 2024-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0063_aidantstatistiques_revoked_mandats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referentsformation',
            name='livestorm_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID livestorm'),
            preserve_default=False,
        ),
    ]
