# Generated by Django 3.1.12 on 2021-08-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0063_merge_20210802_1355"),
        ("aidants_connect_web", "0063_auto_20210803_1511"),
    ]

    operations = []
