# Generated by Django 3.1.12 on 2021-08-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0064_merge_20210804_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habilitationrequest",
            name="email",
            field=models.EmailField(max_length=150),
        ),
    ]
