# Generated by Django 4.2.11 on 2024-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0064_referentsformation_livestorm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreferentnonaidantrequest',
            name='status',
            field=models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'Éligibilité validée'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='status',
            field=models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'Éligibilité validée'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État'),
        ),
    ]
