# Generated by Django 3.1.12 on 2021-08-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_organisation(apps, _):
    Journal = apps.get_model("aidants_connect_web", "Journal")

    for journal in Journal.objects.all():
        journal.organisation = journal.aidant.organisation
        journal.save()


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0065_auto_20210806_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="aidants_connect_web.organisation",
            ),
        ),
        migrations.RunPython(
            populate_organisation, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="journal",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="aidants_connect_web.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="aidant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
