# Generated by Django 4.2.13 on 2024-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0066_habilitationrequest_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreferentnonaidantrequest',
            name='status',
            field=models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'Éligibilité validée'), ('processing_p2p', 'Éligibilité validée (pair-à-pair)'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='status',
            field=models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'Éligibilité validée'), ('processing_p2p', 'Éligibilité validée (pair-à-pair)'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État'),
        ),
    ]
