# Generated by Django 4.2.13 on 2024-06-05 12:26

from django.db import migrations

import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0067_alter_coreferentnonaidantrequest_status_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='habilitationrequest',
            trigger=pgtrigger.compiler.Trigger(name='check_p2p_course_type', sql=pgtrigger.compiler.UpsertTriggerSql(func="-- Prevent concurrent inserts from multiple transactions\nLOCK TABLE aidants_connect_web_habilitationrequest IN EXCLUSIVE MODE;\n\nIF NEW.status = 'processing_p2p' THEN\n    NEW.course_type := '2';\nELSIF NEW.status = 'processing' THEN\n    NEW.course_type := 1;\nEND IF;\n\nRETURN NEW;", hash='e7edacc80d20645e795f994b30282fd1b928d1d5', operation='UPDATE', pgid='pgtrigger_check_p2p_course_type_f167f', table='aidants_connect_web_habilitationrequest', when='BEFORE')),
        ),
    ]
