# Generated by Django 3.1.12 on 2021-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0067_auto_20210817_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="data_pass_id",
            field=models.PositiveIntegerField(null=True, verbose_name="Datapass ID"),
        ),
    ]
