# Generated by Django 3.1.12 on 2021-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0068_organisation_data_pass_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="is_active",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Est active"
            ),
        ),
    ]
