# Generated by Django 4.2.14 on 2024-07-31 07:27

from django.db import migrations

import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0068_habilitationrequest_check_p2p_course_type'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='habilitationrequest',
            name='check_attendants_count',
        ),
    ]
