# Generated by Django 4.2.17 on 2025-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0069_remove_habilitationrequest_check_attendants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitationrequest',
            name='connexion_mode',
            field=models.CharField(blank=True, choices=[('card', 'Carte physique'), ('phone', 'Application mobile')],
                                   default='', max_length=150, null=True, verbose_name='Moyen de connexion'),
        ),
    ]
