# Generated by Django 3.1.12 on 2021-09-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0071_connection_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidant",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_aidants",
                to="aidants_connect_web.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="aidant",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                related_name="aidants",
                to="aidants_connect_web.Organisation",
                verbose_name="Membre des organisations",
            ),
        ),
    ]
