# Generated by Django 4.2.17 on 2025-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0071_habilitationrequest_created_by_fne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitationrequest',
            name='id_fne',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='ID FNE'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='id_fne',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='ID FNE'),
        ),
    ]
