# Generated by Django 4.2.17 on 2025-05-26 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0072_habilitationrequest_id_fne_organisation_id_fne'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAskingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_padding', models.CharField(max_length=16, blank=True, editable=False, null=True)),
                ('user_mobile', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
