# Generated by Django 4.2.17 on 2025-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0073_mobileaskinguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileaskinguser',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobileaskinguser',
            name='user_padding',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
