# Generated by Django 3.1.13 on 2021-11-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0074_auto_20211014_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidant",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_aidants",
                to="aidants_connect_web.organisation",
                verbose_name="Organisation courante",
            ),
        ),
    ]
