# Generated by Django 4.2.17 on 2025-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0074_alter_mobileaskinguser_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='created_by_fne',
            field=models.BooleanField(default=False, verbose_name='Création FNE'),
        ),
        migrations.AddField(
            model_name='aidant',
            name='id_fne',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='ID FNE'),
        ),
    ]
