# Generated by Django 4.2.17 on 2025-06-19 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0075_aidant_created_by_fne_aidant_id_fne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_by_fne',
            field=models.BooleanField(default=False, editable=False, verbose_name='Création FNE'),
        ),
        migrations.CreateModel(
            name='FirstConnexionManagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_secret', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
