# Generated by Django 4.2.17 on 2025-08-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0075_aidant_created_by_fne_aidant_id_fne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_by_fne',
            field=models.BooleanField(default=False, editable=False, verbose_name='Création FNE'),
        ),
    ]
