# Generated by Django 3.1.13 on 2021-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0075_auto_20211110_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="habilitationrequest",
            name="origin",
            field=models.CharField(
                choices=[
                    ("datapass", "Datapass"),
                    ("responsable", "Responsable Structure"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=150,
                verbose_name="Origine",
            ),
        ),
        migrations.AlterField(
            model_name="habilitationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouvelle"),
                    ("processing", "En cours"),
                    ("validated", "Validée"),
                    ("refused", "Refusée"),
                    ("cancelled", "Annulée"),
                ],
                default="new",
                max_length=150,
                verbose_name="État",
            ),
        ),
    ]
