# Generated by Django 3.1.13 on 2021-11-18 15:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0076_auto_20211110_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Téléphone"
            ),
        ),
    ]
