# Generated by Django 4.2.17 on 2025-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0077_firstconnexionmanagerinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstconnexionmanagerinfo',
            name='already_used',
            field=models.BooleanField(default=False),
        ),
    ]
