# Generated by Django 4.2.23 on 2025-09-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0078_firstconnexionmanagerinfo_already_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmailSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('last_sending_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernier envoi')),
                ('code_email', models.CharField(max_length=255, verbose_name='Code email')),
                ('aidant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
