# Generated by Django 4.2.23 on 2025-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0079_logemailsending'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address_complement',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name="Complément d'adresse"),
        ),
    ]
