# Generated by Django 3.2.11 on 2022-02-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0080_add_corse_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="aidants_connect_web.organisation",
            ),
        ),
    ]
