# Generated by Django 4.2.26 on 2025-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0080_organisation_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='is_admin_metier',
            field=models.BooleanField(default=False, verbose_name='Est un administrateur métier'),
        ),
        migrations.AddField(
            model_name='aidant',
            name='is_of_user',
            field=models.BooleanField(default=False, verbose_name='Est un utilisateur Organisame de Frmation'),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='id_fne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID FNE'),
        ),
    ]
