# Generated by Django 4.2.26 on 2025-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0080_organisation_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitationrequest',
            name='email_formateur',
            field=models.EmailField(blank=True, help_text='Email du formateur P2P', max_length=150, null=True, verbose_name='Email du formateur'),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='course_type',
            field=models.IntegerField(choices=[(1, 'Formation classique'), (2, 'Formation entre pairs')], default=1, editable=False, verbose_name='Type de parcours'),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='id_fne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID FNE'),
        ),
    ]
