# Generated by Django 3.2.11 on 2022-02-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0081_auto_20220208_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilitationrequest',
            options={'verbose_name': 'aidant à former', 'verbose_name_plural': 'aidants à former'},
        ),
    ]
