# Generated by Django 4.2.26 on 2026-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0081_aidant_is_admin_metier_aidant_is_of_user_and_more'),
        ('aidants_connect_web', '0081_habilitationrequest_email_formateur_and_more'),
    ]

    operations = [
    ]
