# Generated by Django 3.2.12 on 2022-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0082_alter_habilitationrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='data_pass_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Datapass ID'),
        ),
    ]
