# Generated by Django 4.2.26 on 2026-02-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0082_merge_20260116_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitationrequest',
            name='email_annonce_formateur_pap_send',
            field=models.BooleanField(default=False, editable=False, verbose_name='Email PAP annonce formateur envoyé'),
        ),
        migrations.AddField(
            model_name='habilitationrequest',
            name='email_detail_formateur_pap_send',
            field=models.BooleanField(default=False, editable=False, verbose_name='Email PAP détail formateur envoyé'),
        ),
        migrations.AddField(
            model_name='habilitationrequest',
            name='email_hr_validated_pap_send',
            field=models.BooleanField(default=False, editable=False, verbose_name='Email validation formation pap envoyé'),
        ),
    ]
