# Generated by Django 3.2.12 on 2022-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0083_alter_organisation_data_pass_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('last_id', models.PositiveIntegerField()),
            ],
        ),
    ]
