# Generated by Django 4.2.26 on 2026-02-16 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0083_habilitationrequest_email_annonce_formateur_pap_send_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_emails_sent', models.IntegerField(default=0, verbose_name="Nombre d'emails envoyés")),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier envoi')),
                ('code_email', models.CharField(max_length=50, verbose_name='Code email')),
            ],
            options={
                'verbose_name': "Statistiques d'envoi d'email",
                'verbose_name_plural': "Statistiques d'envois d'email",
            },
        ),
        migrations.CreateModel(
            name='AidantEmailStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_email', models.CharField(max_length=50, verbose_name='Code email')),
                ('sending_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('aidant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.emailstatistics', verbose_name="Type d'email")),
            ],
            options={
                'verbose_name': "Envoi d'email pour un aidant",
                'verbose_name_plural': "Envois d'email pour un aidant",
            },
        ),
    ]
