# Generated by Django 4.2.26 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0084_emailstatistics_aidantemailstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidantemailstats',
            name='infos',
            field=models.TextField(blank=True, null=True, verbose_name='Informations supplémentaire'),
        ),
    ]
