# Generated by Django 4.2.26 on 2026-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0085_aidantemailstats_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='is_of_admin',
            field=models.BooleanField(default=False, verbose_name='Est un administrateur OF'),
        ),
    ]
