# Generated by Django 4.2.26 on 2026-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0086_aidant_is_of_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidant',
            name='is_of_admin',
            field=models.BooleanField(default=False, verbose_name='Est un administrateur Organisme de Formation'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='is_of_user',
            field=models.BooleanField(default=False, verbose_name='Est un utilisateur Organisme de Formation'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='profession',
            field=models.TextField(blank=True),
        ),
    ]
