# Generated by Django 4.2.26 on 2026-03-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0086_aidant_is_of_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidant',
            name='is_of_admin',
            field=models.BooleanField(default=False, verbose_name='Est un administrateur Organisme de Formation'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='is_of_user',
            field=models.BooleanField(default=False, verbose_name='Est un utilisateur Organisme de Formation'),
        ),
        migrations.AlterField(
            model_name='aidant',
            name='profession',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habilitationrequest',
            name='origin',
            field=models.CharField(choices=[('datapass', 'Datapass'), ('responsable', 'Référent Structure'), ('autre', 'Autre'), ('habilitation', 'Formulaire Habilitation'), ('structure_change', 'Changement de structure')], default='autre', max_length=150, verbose_name='Origine'),
        ),
        migrations.CreateModel(
            name='StructureChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('status', models.CharField(choices=[('waitling_list', "Liste d'attente"), ('new', 'Nouvelle'), ('processing', 'Éligibilité validée'), ('processing_p2p', 'Éligibilité validée (pair-à-pair)'), ('validated', 'Validée'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='waitling_list', max_length=150, verbose_name='État')),
                ('created_by_fne', models.BooleanField(default=False, verbose_name='Création FNE')),
                ('id_fne', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID FNE')),
                ('connexion_mode', models.CharField(blank=True, choices=[('card', 'Carte physique'), ('phone', 'Application mobile')], default='', max_length=150, null=True, verbose_name='Moyen de connexion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('formation_done', models.BooleanField(default=False, verbose_name='Formation faite')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Date de formation')),
                ('test_pix_passed', models.BooleanField(default=False, verbose_name='Test PIX')),
                ('date_test_pix', models.DateTimeField(blank=True, null=True, verbose_name='Date test PIX')),
                ('origin', models.CharField(choices=[('datapass', 'Datapass'), ('responsable', 'Référent Structure'), ('autre', 'Autre'), ('habilitation', 'Formulaire Habilitation'), ('structure_change', 'Changement de structure')], default='structure_change', max_length=150, verbose_name='Origine')),
                ('new_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Adresse e-mail (nouvelle structure)')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure_change_requests', to='aidants_connect_web.organisation')),
            ],
            options={
                'verbose_name': 'demande de changement de structure',
                'verbose_name_plural': 'demandes de changement de structure',
            },
        ),
        migrations.AddConstraint(
            model_name='structurechangerequest',
            constraint=models.UniqueConstraint(fields=('email', 'organisation'), name='structurechangerequest_unique_email_per_orga'),
        ),
    ]
