# Generated by Django 4.2.26 on 2026-03-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0087_alter_aidant_is_of_admin_alter_aidant_is_of_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('new_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Adresse e-mail (nouvelle structure)')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('validated', 'Validée'), ('refused', 'Refusée'), ('status_cancelled_by_responsable', 'Annulée par le ou la référente')], default='new', max_length=150, verbose_name='État')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('aidant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Aidant')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_change_requests', to='aidants_connect_web.organisation', verbose_name='Nouvelle structure')),
                ('previous_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_structure_change_requests', to='aidants_connect_web.organisation', verbose_name='Ancienne structure')),
            ],
            options={
                'verbose_name': 'demande de changement de structure',
                'verbose_name_plural': 'demandes de changement de structure',
            },
        ),
        migrations.AddConstraint(
            model_name='structurechangerequest',
            constraint=models.UniqueConstraint(fields=('email', 'organisation'), name='structurechangerequest_unique_email_per_orga'),
        ),
    ]
