# Generated by Django 4.2.29 on 2026-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0089_coreferentnonaidantrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='attestation',
            field=models.FileField(blank=True, null=True, upload_to='attestation', verbose_name='Attestation AidantConnect'),
        ),
    ]
