# Generated by Django 4.2.29 on 2026-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aidants_connect_web", "0090_aidant_attestation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structurechangerequest",
            name="previous_organisation",
        ),
        migrations.AddField(
            model_name="structurechangerequest",
            name="previous_organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structures dont l'aidant était membre avant la demande (hors nouvelle structure). Retirées du compte à la validation.",
                related_name="structure_change_requests_as_previous",
                to="aidants_connect_web.organisation",
                verbose_name="Anciennes structures",
            ),
        ),
    ]
