# Generated by Django 4.2.30 on 2026-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0091_remove_structurechangerequest_previous_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitationrequest',
            name='pix_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note PIX'),
        ),
    ]
