# Generated by Django 4.2.30 on 2026-07-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0092_habilitationrequest_pix_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='invalid_siret',
            field=models.BooleanField(default=False, verbose_name='Siret Invalide'),
        ),
    ]
