# Generated by Django 4.2.30 on 2026-07-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0092_habilitationrequest_pix_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journal',
            name='infos_set_remote_mandate_by_sms',
        ),
    ]
