# Generated by Django 4.2.30 on 2026-07-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0093_remove_journal_infos_set_remote_mandate_by_sms'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connection',
            name='connection_user_phone_set',
        ),
        migrations.RemoveConstraint(
            model_name='connection',
            name='connection_consent_request_id_set',
        ),
        migrations.RemoveConstraint(
            model_name='mandat',
            name='mandat_consent_request_id_set',
        ),
        migrations.AlterField(
            model_name='connection',
            name='remote_constent_method',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Par signature sur papier')], max_length=200, verbose_name='Méthode de consentement à distance'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='remote_constent_method',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Par signature sur papier')], max_length=200, verbose_name='Méthode de consentement à distance'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='remote_constent_method',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Par signature sur papier')], max_length=200, verbose_name='Méthode de consentement à distance'),
        ),
    ]
