# Generated by Django 4.2.30 on 2026-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0093_organisation_invalid_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='doublon_siret',
            field=models.BooleanField(blank=True, default=False, verbose_name='Siret en Doublon'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='invalid_siret',
            field=models.BooleanField(blank=True, default=False, verbose_name='Siret Invalide'),
        ),
    ]
