# Generated by Django 4.2.30 on 2026-07-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0094_organisation_doublon_siret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='legal_cat_level_one',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Niveau I catégories juridiques'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='legal_cat_level_three',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Niveau III catégories juridiques'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='legal_cat_level_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Niveau II catégories juridiques'),
        ),
    ]
