# Generated by Django 4.2.29 on 2026-09-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0096_organisation_demarches_configured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidant',
            name='is_cdd_user',
            field=models.BooleanField(default=False, verbose_name='Est un utilisateur Caisse des dépots'),
        ),
    ]
