# Generated by Django 4.2.29 on 2026-09-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0097_aidant_is_cdd_user'),
        ('aidants_connect_web', '0097_aidantstatistiques_number_active_mandats_and_more'),
    ]

    operations = [
    ]
