# Generated by Django 4.2.29 on 2026-10-05 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0098_merge_20260922_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='aidant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
