# Generated by Django 2.2 on 2019-04-23 15:55

import aidant_connect_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=99)),
                ('code', models.CharField(max_length=100)),
                ('expiresOn', models.DateTimeField(default=aidant_connect_web.models.default_expiration_date)),
            ],
        ),
    ]
