# Generated by Django 4.0.8 on 2023-01-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aidants_connect_web', '0016_alter_habilitationrequest_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('tracking', models.CharField(blank=True, max_length=200, null=True, verbose_name='Information transporteur')),
                ('command_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bon commande client')),
                ('sending_date', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('status', models.CharField(choices=[('preparing', 'En préparation'), ('sending', "En cours d'envoi"), ('received', 'Colis livré'), ('lost', 'Colis perdu'), ('returned', 'Colis retour')], max_length=200, verbose_name="statut d'envoi")),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sendings', to='aidants_connect_web.organisation', verbose_name='Organisation')),
            ],
        ),
    ]
