# Generated by Django 4.0.8 on 2023-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsending',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'En préparation'), ('SENDING', "En cours d'envoi"), ('RECEIVED', 'Colis livré'), ('LOST', 'Colis perdu'), ('RETURNED', 'Colis retour')], max_length=200, verbose_name="statut d'envoi"),
        ),
    ]
