# Generated by Django 4.2.1 on 2023-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_erp', '0003_cardsending_referent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsending',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'En préparation'), ('SENDING', "En cours d'envoi"), ('RECEIVED', 'Colis livré'), ('WAITING', 'En attente'), ('LOST', 'Colis perdu'), ('RETURNED', 'Colis retour')], max_length=200, verbose_name="statut d'envoi"),
        ),
    ]
