# Generated by Django 4.2.17 on 2025-02-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_erp', '0004_alter_cardsending_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsending',
            old_name='responsable',
            new_name='bizdev',
        ),
        migrations.RenameField(
            model_name='cardsending',
            old_name='code_responsable',
            new_name='code_referent',
        ),
        migrations.AddField(
            model_name='cardsending',
            name='email_referent',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Email referent (GRIST)'),
        ),
        migrations.AddField(
            model_name='cardsending',
            name='name_referent',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Nom referent (GRIST)'),
        ),
        migrations.AddField(
            model_name='cardsending',
            name='phone_referent',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Telephone referent (GRIST)'),
        ),
    ]
