# Generated by Django 4.0.8 on 2023-03-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidants_connect_erp', '0004_cardsending_code_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsending',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent_for_sendings', to=settings.AUTH_USER_MODEL),
        ),
    ]
