# Generated by Django 4.2.17 on 2025-02-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_erp', '0005_rename_responsable_cardsending_bizdev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsending',
            name='id_grist',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, null=True, verbose_name='Id Grist'),
        ),
    ]
