# Generated by Django 4.2.17 on 2025-02-27 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidants_connect_erp', '0006_cardsending_id_grist_fne'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsending',
            name='aidants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name="Aidants concernés par l'envoi"),
        ),
        migrations.AddField(
            model_name='cardsending',
            name='estimated_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de cartes estimé'),
        ),
    ]
