# Generated by Django 4.2.17 on 2025-05-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_erp', '0007_cardsending_aidants_cardsending_estimated_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsending',
            name='kit_quantity',
        ),
    ]
