# Generated by Django 4.2.17 on 2025-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_erp', '0008_remove_cardsending_kit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsending',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de cartes'),
        ),
    ]
