# Generated by Django 3.2.15 on 2022-08-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('insee_code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Code INSEE')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de région')),
            ],
            options={
                'verbose_name': 'Région',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('insee_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Code INSEE')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Code Postal')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du département')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='aidants_connect_common.region')),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
    ]
