# Generated by Django 4.2.2 on 2023-06-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('insee_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Code INSEE')),
                ('name', models.TextField(verbose_name='Nom de la commune')),
                ('zrr', models.BooleanField(default=False, verbose_name='Commune classé en zone rurale restreinte')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune', to='aidants_connect_common.department')),
            ],
        ),
    ]
