# Generated by Django 4.2.6 on 2023-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0002_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_email', models.TextField(verbose_name="Contenu de l'email au format texte")),
                ('html_email', models.TextField(verbose_name="Contenu de l'email au format HTML")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('email_adress', models.CharField(max_length=250, verbose_name='Adresse email')),
            ],
        ),
    ]
