# Generated by Django 4.2.7 on 2023-12-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0003_emaildebug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailDebug',
        ),
    ]
