# Generated by Django 4.2.10 on 2024-03-05 09:50

import django.db.models.deletion
from django.db import migrations, models

import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0001_20220329_stable_schema'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('aidants_connect_common', '0004_delete_emaildebug'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='IdGenerator',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=100, unique=True)),
                        ('last_id', models.PositiveIntegerField()),
                    ],
                ),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Date et heure de début de la formation')),
                ('end_datetime', models.DateTimeField(verbose_name='Date et heure de fin de la formation')),
                ('duration', models.IntegerField(verbose_name='Durée en heures')),
                ('max_attendants', models.IntegerField(verbose_name="Nombre maximum d'inscrits possibles")),
                ('status', models.IntegerField(choices=[(1, 'En présentiel'), (2, 'À distance')], verbose_name='En présentiel/à distance')),
                ('place', models.CharField(max_length=500, verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Formation aidant',
                'verbose_name_plural': 'Formations aidant',
            },
        ),
        migrations.CreateModel(
            name='FormationAttendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendant_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Type de formation aidant',
                'verbose_name_plural': 'Types de formation aidant',
            },
        ),
        migrations.AddConstraint(
            model_name='formationtype',
            constraint=models.CheckConstraint(check=models.Q(('label__isnull_or_blank', False)), name='not_blank_label'),
        ),
        migrations.AddField(
            model_name='formationattendant',
            name='attendant_content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_formations_attendants', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='formationattendant',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendants', to='aidants_connect_common.formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidants_connect_common.formationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='formationattendant',
            unique_together={('attendant_content_type', 'attendant_id', 'formation')},
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='must_starts_before_it_ends'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', 0)), name='must_be_a_non_0_duration'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('max_attendants__gt', 0)), name='cant_have_0_max_attendants'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='formationattendant',
            trigger=pgtrigger.compiler.Trigger(name='check_attendants_count', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE attendants_count INTEGER; max_attendants_count INTEGER;', func="-- prevent concurrent inserts from multiple transactions\nLOCK TABLE aidants_connect_common_formationattendant IN EXCLUSIVE MODE;\n\nSELECT INTO attendants_count COUNT(*) \nFROM aidants_connect_common_formationattendant \nWHERE formation_id = NEW.formation_id;\n\nSELECT max_attendants INTO max_attendants_count\nFROM aidants_connect_common_formation \nWHERE id = NEW.formation_id;\n\nIF attendants_count >= max_attendants_count THEN\n    RAISE EXCEPTION 'Formation is already full.' USING ERRCODE = 'check_violation';\nEND IF;\n\nRETURN NEW;", hash='8f5532229ae9079ce0c147c6f3f39d5069d110a5', operation='INSERT OR UPDATE', pgid='pgtrigger_check_attendants_count_de7ba', table='aidants_connect_common_formationattendant', when='BEFORE')),
        ),
    ]
