# Generated by Django 4.2.8 on 2024-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0006_alter_formationattendant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formation',
            name='id_grist',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, verbose_name='Id Grist'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin de la formation'),
        ),
    ]
