# Generated by Django 4.2.11 on 2024-04-15 14:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0007_formation_description_formation_id_grist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nom')),
                ('contacts', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None)),
            ],
            options={
                'verbose_name': 'Formation\xa0: organisation',
                'verbose_name_plural': 'Formation\xa0: organisation',
            },
        ),
        migrations.AddConstraint(
            model_name='formationorganization',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull_or_blank', False)), name='not_blank_name'),
        ),
        migrations.AddField(
            model_name='formation',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='aidants_connect_common.formationorganization'),
        ),
    ]
