# Generated by Django 4.2.11 on 2024-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0008_formationorganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationattendant',
            name='id_grist',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, verbose_name='Id Grist'),
        ),
    ]
