# Generated by Django 4.2.11 on 2024-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0009_formationattendant_id_grist'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationattendant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='formationattendant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification'),
        ),
    ]
