# Generated by Django 4.2.11 on 2024-04-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0010_formationattendant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationattendant',
            name='organization_warned_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Lʼorganisation de la formation a été informée de lʼinscription de cette personne à…'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='aidants_connect_common.formationorganization'),
        ),
    ]
