# Generated by Django 4.2.11 on 2024-04-24 07:38

from django.db import migrations

import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0011_formationattendant_organization_warned_at_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='formationattendant',
            name='check_attendants_count',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='formationattendant',
            trigger=pgtrigger.compiler.Trigger(name='check_attendants_count', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE attendants_count INTEGER; max_attendants_count INTEGER;', func="-- prevent concurrent inserts from multiple transactions\nLOCK TABLE aidants_connect_common_formationattendant IN EXCLUSIVE MODE;\n\nSELECT INTO attendants_count COUNT(*)\nFROM aidants_connect_common_formationattendant\nWHERE formation_id = NEW.formation_id;\n\nSELECT max_attendants INTO max_attendants_count\nFROM aidants_connect_common_formation\nWHERE id = NEW.formation_id;\n\nIF attendants_count >= max_attendants_count THEN\n    RAISE EXCEPTION 'Formation is already full.' USING ERRCODE = 'check_violation';\nEND IF;\n\nRETURN NEW;", hash='c78847f0f3384d401bd84ca669d924c5fb454794', operation='INSERT', pgid='pgtrigger_check_attendants_count_de7ba', table='aidants_connect_common_formationattendant', when='BEFORE')),
        ),
    ]
