# Generated by Django 4.2.11 on 2024-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0014_remove_formationattendant_check_attendants_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formation',
            name='must_starts_before_it_ends',
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('start_datetime__lte', models.F('end_datetime'))), name='must_starts_before_or_equal_it_ends'),
        ),
    ]
