# Generated by Django 4.2.14 on 2024-07-31 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_web', '0069_remove_habilitationrequest_check_attendants_count'),
        ('aidants_connect_common', '0015_remove_formation_must_starts_before_it_ends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationattendant',
            name='attendant_2',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_web.habilitationrequest'),
        ),
        migrations.RunSQL(
            """
            UPDATE aidants_connect_common_formationattendant at
            SET attendant_2_id = at.attendant_id
            FROM django_content_type t
            WHERE t.id = at.attendant_content_type_id
                AND t.app_label = 'aidants_connect_web'
                AND t.model = 'habilitationrequest'
            """,
            elidable=True
        ),
        migrations.RunSQL(
            """
            DELETE FROM aidants_connect_common_formationattendant
            WHERE attendant_2_id = NULL
            """,
            elidable=True
        ),
        migrations.AlterUniqueTogether(
            name='formationattendant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='formationattendant',
            name='attendant_content_type',
        ),
        migrations.RemoveField(
            model_name='formationattendant',
            name='attendant_id',
        ),
        migrations.RenameField(
            model_name='formationattendant',
            old_name='attendant_2',
            new_name='attendant',
        ),
        migrations.AlterField(
            model_name='formationattendant',
            name='attendant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='aidants_connect_web.habilitationrequest',
                related_name='formations',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='formationattendant',
            unique_together={('attendant', 'formation')},
        ),
    ]
