# Generated by Django 4.2.17 on 2025-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0018_formationorganization_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='intra',
            field=models.BooleanField(default=False, verbose_name='Session intra'),
        ),
    ]
