# Generated by Django 4.2.17 on 2025-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0020_alter_formation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='publish_or_not',
            field=models.BooleanField(default=True, verbose_name="Publie sur le site, disponible à l'inscription"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duration',
            field=models.IntegerField(choices=[(7, '7 heures'), (14, '14 heures')], verbose_name='Durée en heures'),
        ),
    ]
