# Generated by Django 4.2.17 on 2025-06-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0021_formation_publish_or_not_alter_formation_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationContactPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_common.formationorganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormationContactPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidants_connect_common.formationorganization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
