# Generated by Django 4.2.23 on 2025-08-27 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidants_connect_common', '0022_formationcontactpublic_formationcontactprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationorganization',
            name='users_of',
            field=models.ManyToManyField(limit_choices_to={'is_of_user': True}, related_name='organizations_formations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs OF de'),
        ),
    ]
