# Generated by Django 4.2.23 on 2025-09-10 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0023_formationorganization_users_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfDayClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Date et heure de début de la demi-journée')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidants_connect_common.formation')),
            ],
            options={
                'verbose_name': 'Demi-journée de formation',
                'verbose_name_plural': 'Demi-journées de formation',
            },
        ),
    ]
