# Generated by Django 4.2.26 on 2025-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0024_halfdayclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfdayclass',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin de la demi-journée'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='publish_or_not',
            field=models.BooleanField(default=False, verbose_name="Publie sur le site, disponible à l'inscription"),
        ),
    ]
