# Generated by Django 4.2.26 on 2026-02-12 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidants_connect_common', '0025_halfdayclass_end_time_alter_formation_publish_or_not'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='formationattendant',
            options={'verbose_name': 'inscrit', 'verbose_name_plural': 'Inscrits'},
        ),
        migrations.AlterModelOptions(
            name='formationorganization',
            options={'verbose_name': 'Organisme de formation', 'verbose_name_plural': 'Organismes de formation'},
        ),
        migrations.AlterModelOptions(
            name='formationtype',
            options={'verbose_name': 'Type de formation', 'verbose_name_plural': 'Types de formation'},
        ),
        migrations.AlterField(
            model_name='formationattendant',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='aidants_connect_web.habilitationrequest', verbose_name='Aidant inscrit'),
        ),
        migrations.AlterField(
            model_name='formationattendant',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendants', to='aidants_connect_common.formation', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='formationorganization',
            name='users_of',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_of_user': True}, related_name='organizations_formations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs OF de'),
        ),
        migrations.AlterField(
            model_name='halfdayclass',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='half_day_classes', to='aidants_connect_common.formation'),
        ),
    ]
