# Generated by Django 4.2.26 on 2026-03-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_common', '0026_alter_formation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingConum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nom de financement')),
            ],
            options={
                'verbose_name': 'Financement Conum',
                'verbose_name_plural': 'Financement Conum',
            },
        ),
        migrations.AlterField(
            model_name='formationattendant',
            name='state',
            field=models.IntegerField(choices=[(1, 'Par défaut'), (2, 'En attente'), (3, 'Annulé'), (4, 'Inscrit')], default=1, verbose_name='État de la demande'),
        ),
        migrations.AddField(
            model_name='formationattendant',
            name='financement_conum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidants_connect_common.fundingconum'),
        ),
    ]
